metomi/rose

lib/python/rose/gtk/choice.py

rose edit: edit choices in choice widget

---

doc/rose-rug-advanced-tutorials-arch.html
doc/rose.html

Added a rose arch tutorial to the documentation.
Address part of #898.

rose doc: rose arch advanced tutorial

---

doc/rose-install.html

And:
* More tips on `lib/bash/rose_init_site`.
* Syntax highlight for embedded shell scripts.

install doc: more tips on python-requests

---

doc/rose-rug-advanced-tutorials-arch.html
doc/rose.html

Moved link location in the top level and gramma/typo correction.

rose doc: rose arch update

---

lib/python/rose/run.py
t/rose-app-run/21-run-config-load-event.t

Report loading of a run configuration.
Close #1502.

rose.run.RunConfigLoadEvent: new event

---

bin/rose-suite-clean
doc/rose-command.html

rose suite-clean --only=ITEM documentation

---

lib/python/rosie/ws_client.py
lib/python/rosie/ws_client_auth.py

rosie.ws_client: handle KeyboardInterrupt

---

lib/python/rosie/vc.py
t/rosie-create/00-basic.t

rosie create: improve prompt

---

etc/rose-meta/rose_prune/HEAD/rose-meta.conf

Update rose prune metadata to include server log pruning setting

---

doc/rose-install.html

Rosie now requires Subversion 1.8

---

lib/python/rose/app_run.py
t/rose-app-run/08-poll.t

Support ISO8601 duration in poll delays syntax. Improve problem
reporting on problem with legacy syntax.
Fix #1552.

rose app-run: poll delays: ISO8601 duration

---

doc/rose-rug-suite-writing-tutorial.html

This adds a brief bit of version control information into the suite writing tutorial.

rose documentation: suite writing tutorial: mention fcm add, commit

---

lib/python/rose/config_editor/data.py

rose edit: better handling of bad metadata imports

---

lib/python/rose/config_editor/page.py

Closes #1520 
Presents the full page of information,

rose edit: full page

---

doc/rose-install.html

How to test that the built-in Rosie web service server is up and
running.
How to deploy site configuration metadata. Close #1329.

Improve install doc

---

lib/python/rose/bush.py

rose bush: unify HTTP 403 or 404 returns

---

t/rose-ana/00-run-basic.t
t/rose-ana/00-run-basic/app/rose_ana_t1/file/kgo.txt
t/rose-ana/00-run-basic/app/rose_ana_t1/file/results.txt
t/rose-ana/00-run-basic/app/rose_ana_t1/rose-app.conf
t/rose-ana/00-run-basic/suite.rc
t/rose-ana/test_header

This is a first attempt at dealing with #775 (long overdue, sorry). This should give some basic tests of at least some of the rose-ana functionality. I've tried to keep away from UM-specific tests, but there's some scope for improvement. I do think any testing is better than no testing, so I'll submit this now.
These tests are updated for #1574, so they won't pass on our current site-default Rose.

Add basic rose-ana test battery

---

lib/python/rosie/db_create.py
lib/python/rosie/svn_post_commit.py

rosa db-create: turn off post-commit notification

---

lib/python/rose/apps/rose_ana.py
t/lib/bash/test_header
t/rose-ana/00-run-basic.t
t/rose-ana/00-run-basic/app/rose_ana_t2/file/kgo.txt
t/rose-ana/00-run-basic/app/rose_ana_t2/file/results.txt
t/rose-ana/00-run-basic/app/rose_ana_t2/opt/rose-app-deactivate.conf
t/rose-ana/00-run-basic/app/rose_ana_t2/rose-app.conf
t/rose-ana/00-run-basic/suite.rc

An attempt to fix #1585 by checking that a non-None value is return from self.config.get_value().
@matthewrmshin, there might be a better way of doing this, would you mind taking a look and reviewing when you get a minute?

Allow ignoring tasks in rose_ana

---

doc/rose-command.html
doc/rose-rosie-advice.html
doc/rose-rug-advanced-tutorials-suicide.html
doc/rose-rug-suite-control.html
doc/rose.html

rose doc: suite-shutdown args, suicide trigger examples, tweak contents listing

---

lib/python/rose/run_source_vc.py
lib/python/rosie/suite_id.py
t/rosie-id/00-basic.t

(Also works if `PWD` is `~/cylc-run/SUITE` or a sub-directory of.)
Close #1534.

rosie id: accept ~/cylc-run/SUITE as argument

---

etc/rose.conf.example
lib/python/rosie/ws_client_auth.py

Specific password stores can now be configured for each prefix per
site/user.

rosie.ws_client_auth: configurable password stores

---

lib/python/rose/config_dump.py
lib/python/rose/config_editor/main.py
lib/python/rose/formats/namelist.py
lib/python/rose/macro.py
t/rose-app-upgrade/09-bad-upgrade-macro.t

Closes #1569 
@benfitzpatrick please review

rose macro and config-edit: namelist options fail if uppercase

---

doc/rose-rug-advanced-tutorials-upgrade-dev.html

Tweak instructions for sub-directory creation so people don't get ahead of themselves and miss a step.
@benfitzpatrick - please review.

rose doc: Tweak upgrade development tutorial wording.

---

t/rose.extra-pyc/00-simple.t
t/rose.extra-pyc/test_header

This will hopefully get rid of problems like #1605.

rose test-battery: check for extra .pyc files

---

lib/html/rose-bush/cycles.html
lib/html/rose-bush/jobs.html
lib/html/rose-bush/rose-bush.css

rose bush: page navigation always visable bottom

---

lib/python/rosie/browser/util.py

Display data source URL in menu item label.

rosie go: display data source URL

---

lib/python/rosie/vc.py
t/rosie-create/00-basic.t

rosie copy: svn log message fix

---

lib/python/rose/apps/rose_prune.py
lib/python/rose/bush.py
lib/python/rose/host_select.py
lib/python/rose/suite_clean.py
lib/python/rose/suite_engine_procs/cylc.py
lib/python/rose/suite_run.py
t/rose-host-select/02-localhost.t

Now check for "localhost", its hostname, its fqdn hostname, and the
associated IP addresses.
Close #1619. @benfitzpatrick please test and review.

rose.host_select: improve check of local host

---

doc/rose-configuration-metadata.html

Document array pattern metadata usage

---

lib/html/rose-bush/cycles.html
lib/python/rose/bush.py
lib/python/rose/suite_engine_procs/cylc.py

rose bush: cycles add new->old/old->new button

---

doc/rose-rug-advanced-tutorials-arch.html
doc/rose-rug-advanced-tutorials-suicide.html

rose doc: expand/collapse button fix

---

doc/rose-rug-task-run.html

Doc: more HTML syntax fix

---

t/rose-task-run/28-env-path-run-path.t
t/rose-task-run/28-env-path-run-path/app/t1/rose-app.conf
t/rose-task-run/28-env-path-run-path/opt/earth/bin/hello
t/rose-task-run/28-env-path-run-path/opt/world/bin/hello
t/rose-task-run/28-env-path-run-path/suite.rc

Ensure that D2 is prepend to PATH.
This change proves that the description of #1608 is invalid.

t: task-env --path=D1 then task-run --path=D2

---

t/rose-task-run/15-app-prune-extglob/suite.rc
t/rose-task-run/29-app-prune-extglob-remote
t/rose-task-run/29-app-prune-extglob-remote.t

New test to sanity check that the functionality is working correctly.

t: prune with extglob on a remote job host

---

lib/python/rose/suite_clean.py
t/rose-suite-clean/08-rmdir.t
t/rose-suite-clean/08-rmdir/app/t-1/rose-app.conf
t/rose-suite-clean/08-rmdir/rose-suite.conf
t/rose-suite-clean/08-rmdir/suite.rc

rose suite-clean: clean empty top directory

---

lib/python/rosie/browser/main.py

Closes #1662 
@benfitzpatrick - please review 1.
@kaday - please review 2.

rosie go: delete option sensitivity different usernames fix

---

lib/python/rose/suite_engine_procs/cylc.py
t/rose-suite-restart/00-no-run.t
t/rose-suite-run/15-reload-rc.t

Compatibility change for cylc/cylc#1480.
@kaday @arjclark please review.

rose suite-scan: handle new cylc scan output

---

lib/html/rose-bush/jobs.html

Provides a hover over for Display Options "reset" and "update"

rose bush: display options improvements

---

bin/rose-suite-shutdown
doc/rose-command.html

rose suite-shutdown: option arg useage update

---

bin/rosie-create
doc/rose-command.html
etc/rose-meta/rose-suite-info/rose-meta.conf
lib/python/rose/__init__.py
lib/python/rose/macro.py
lib/python/rose/metadata_check.py
lib/python/rose/opt_parse.py
lib/python/rosie/browser/__init__.py
lib/python/rosie/vc.py
t/rosie-create/00-basic.t
t/rosie-create/01-copy-edit
t/rosie-create/01-copy.t

Addresses components 3-7 of #1632 
I will update this to closes once I have finished all the components.

rosie: rose-suite.info development

---

lib/python/rosie/ws_client.py
t/rosie-ls/00-basic.t
t/rosie-ls/01-many.t

Fix #1679.
@kaday @arjclark please review.

rosie ls: fix crash when many suites checked out

---

t/rose-cli-bash-completion/00-static.t

Fix test broken by #1701

---

doc/rose-api.html
doc/rose-configuration.html
doc/rose-rug-files.html
doc/rose-rug-introduction.html

Noticed references to issue-list and have removed them.

rose doc: remove issue-list ref

---

doc/rose-rug-task-run.html
lib/python/rose/apps/rose_arch.py
t/rose-task-run/30-app-arch-opt-source.t
t/rose-task-run/30-app-arch-opt-source/app/archive1/rose-app.conf
t/rose-task-run/30-app-arch-opt-source/app/archive2/rose-app.conf
t/rose-task-run/30-app-arch-opt-source/bin/foo
t/rose-task-run/30-app-arch-opt-source/suite.rc

Using the `(NAME)` or `(GLOB)` syntax.
Close #1707.
@arjclark @kaday please review. You can now do:
```cfg
[arch:hello/]
sources=earth.txt (mars.txt) (venus.txt)
```

rose_arch: allow source to be optional

---

doc/rose-rug-metadata.html

Noticed that this was missing from the doc

rose doc: Updated to include value

---

doc/rose-rug-metadata.html

As discussed 
@benfitzpatrick please review

rose doc: metatdata doc highlights

---

lib/python/rosie/vc.py

rosie create: meta_suite_mode should be False

---

lib/python/rose/config_cli.py
lib/python/rose/config_diff.py
lib/python/rose/config_editor/main.py
lib/python/rose/macro.py
lib/python/rose/metadata_check.py
lib/python/rose/metadata_gen.py
lib/python/rose/metadata_graph.py
lib/python/rose/upgrade.py
lib/python/rosie/browser/main.py
lib/python/rosie/svn_pre_commit.py
lib/python/rosie/vc.py
t/rosa-svn-pre-commit/00-basic.t
t/rosa-svn-pre-commit/02-passwd.t
t/rosa-svn-pre-commit/03-meta.t

Validate entries in `trunk/rose-suite.info` for suites.
Close #1702. @benfitzpatrick @kaday please review.

rosa svn-pre-commit: perform macro validate

---

t/rose-task-run/00-run-basic.t
t/rose-task-run/00-run-basic/suite.rc
t/rose-task-run/02-env-basic/suite.rc
t/rose-task-run/04-run-path-empty.t
t/rose-task-run/04-run-path-empty/suite.rc
t/rose-task-run/08-app-fcm-make/suite.rc

This updates several of the older rose task-run tests to use ISO8601 syntax.
@matthewrmshin - please review 1
@kaday - please review 2

Test battery: rose task-run tests: Update tests to ISO8601

---

t/rose-bush/00-basic.t
t/rose-bush/test_header
t/rosie-disco/00-basic.t
t/rosie-id/00-basic.t

1st step for #1010. More to come.

t: basic tests for Rose Bush

---

lib/html/template/rose-bush/view.html

Close #1088. @benfitzpatrick @arjclark please review.

Rose Bush: file view: now recognise [DEBUG]

---

lib/python/rose/suite_engine_procs/cylc.py
lib/python/rose/ws.py
t/rose-bush/00-basic.t

Rose Bush jobs view can now use the `task_job_logs` table in
`cylc-suite.db`.
Close #1646.

rose bush: jobs: cylc-suite.db task_job_logs table

---

t/rose-suite-run/20-pgrep-conflict.t

This change will allow the test to pass on Ubuntu 14.04 boxes.
@arjclark please review. (I don't think a 2nd review is necessary for this.)

t: handle new version of `pgrep`

---

t/rose-task-run/32-app-arch-compressed.t
t/rose-task-run/32-app-arch-compressed/app/archive/rose-app.conf
t/rose-task-run/32-app-arch-compressed/suite.rc

New test to prove that we are OK archiving already compressed files.

t: rose_arch: archive already compressed files

---

doc/rose-configuration-metadata.html

Fix link to point at right location.
@matthewrmshin - please review. Doesn't need 2nd review.

Documentation: Fix dead link.

---

bin/rose-test-battery
doc/rose-command.html

@arjclark please review. (Only a doc change for a developer command, so 1 reviewer is probably enough.)

Improve test-battery doc

---

t/rose-bush/03-no-statuses.t
t/rose-bush/03-no-statuses/suite.rc

Test for #1762.
@arjclark please review. (1 review is probably OK for this.)

test battery: rose-bush: jobs list status filter

---

bin/rose-suite-log
doc/rose-command.html

The command no longer updates the viewer.
@arjclark please review. Please assign review 2 if you think it is necessary.

doc: rose suite-log: update

---

doc/rose-api.html

This change updates a few one-liners in this doc.
@arjclark please review. (I think a review 1 is enough.)

doc: rose-api: updated

---

lib/html/template/rose-bush/jobs.html
lib/python/rose/bush.py
lib/python/rose/suite_engine_procs/cylc.py
t/lib/bash/test_header
t/rose-bush/04-time-sort.t
t/rose-bush/04-time-sort/rose-suite.info
t/rose-bush/04-time-sort/suite.rc

Sort by descending or ascending:
* time submit
* time run start
* time run exit
* duration queue
* duration run
* duration queue+run
Close #1018.

rose bush: jobs list: sort by time, duration, etc

---

lib/python/rose/suite_engine_procs/cylc.py
t/rose-bush/05-cycles-job-fails.t
t/rose-bush/05-cycles-job-fails/rose-suite.info
t/rose-bush/05-cycles-job-fails/suite.rc

Presence of statement arguments for query causes the query to do nothing.

rose bush: cycles: fix job fails count

---

doc/rose-rug-advanced-tutorials-bunch.html

Fixes doc/rose-rug-advanced-tutorials-bunch.html problems highlighted by test battery.
Apologies.

Fix test battery flagged problems.

---

doc/rose-rug-task-run.html
lib/python/rose/app_run.py
lib/python/rose/apps/rose_prune.py
lib/python/rose/date.py
t/rose-task-run/33-app-prune-cycle-format.t
t/rose-task-run/33-app-prune-cycle-format/app/pruner/rose-app.conf
t/rose-task-run/33-app-prune-cycle-format/suite.rc

rose_prune: support custom cycle format

---

doc/rose-rug-advanced-tutorials-trigger.html

Some minor tweaks to the triggers tutorial following last Rose training course.

Tweak triggers tutorial

---

etc/rose.conf.example
lib/html/template/rose-bush/index.html
lib/html/template/rose-bush/suite-base.html
lib/html/template/rose-bush/suites.html
lib/python/rose/bush.py
t/rose-bush/01-title.t

rose bush: configurable logo

---

etc/rose.conf.example
lib/html/template/rose-bush/cycles.html
lib/html/template/rose-bush/jobs.html
lib/html/template/rose-bush/pager.html
lib/html/template/rose-bush/suites.html
lib/python/rose/bush.py
t/rose-bush/00-basic.t
t/rose-bush/01-title.t
t/rose-bush/02-no-job-out.t
t/rose-bush/03-no-statuses.t
t/rose-bush/04-time-sort.t
t/rose-bush/05-cycles-job-fails.t
t/rose-bush/07-cycles-page.t
t/rose-bush/08-suites-page.t

Display Options box is now on suites list and cycles list.
Entries per page option for suites list and cycles list.
Suites list can now be filtered by suite names.
Suites list can now be ordered by suite name as well as activity time.
Close #1721.

rose bush: improve paging and sorting

---

lib/html/template/rose-bush/cycles.html
lib/html/template/rose-bush/jobs.html
lib/html/template/rose-bush/suite-base.html
lib/html/template/rose-bush/suite-state.html
lib/python/rose/suite_engine_procs/cylc.py
t/rose-bush/06-host-port.t

Take advantage of cylc/cylc#1705

rose bush: cycles/jobs: display suite host:port

---

t/rose-bush/06-host-port.t

Detect for non-zero size in port file, instead of just existence.

t: rose-bush 06: improve robustness

---

lib/html/static/js/rose-bush.js
lib/html/template/rose-bush/job-entry.html
lib/html/template/rose-bush/jobs.html
lib/html/template/rose-bush/pager.html
lib/python/rose/bush.py
lib/python/rose/suite_engine_procs/cylc.py
t/rose-bush/00-basic.t
t/rose-bush/09-jobs-fuzzy-time.t
t/rose-bush/10-jobs-task-status.t

Fuzzy time toggle is now preserved when paging.
Location and times are now in their own columns.
A submit number badge is now:
* a link to select all jobs of a given point/task.
* displaying the number of jobs in a given point/task.
* displaying the task status by colour of the point/task.
Close #1789.

rose bush: job entry: improve fuzzy time + layout

---

lib/python/rosie/svn_post_commit.py
t/rosa-svn-post-commit/03-unicode.t
t/rosie-lookup/02-unicode.t

Only pass "utf-8" strings to discovery database.
@benfitzpatrick @kaday please review.

rosa svn-post-commit: decode DB strings to utf-8

---

CONTRIBUTING.md
doc/rose-rug-task-run.html

Corrected a minor typo and updated CONTRIBUTING.md
@matthewrmshin please review.

minor-typo-fix

---

lib/python/rose/host_select.py

Also improve robustness when parsing scores.

rose host-select: mem: improve `free -m` parser

---

lib/python/rose/apps/comparisons/cumf.py
lib/python/rose/config.py
lib/python/rose/config_editor/menu.py
lib/python/rose/config_editor/menuwidget.py
lib/python/rose/config_editor/ops/group.py
lib/python/rose/config_editor/ops/section.py
lib/python/rose/config_editor/ops/variable.py
lib/python/rose/config_editor/page.py
lib/python/rose/config_editor/pagewidget/table.py
lib/python/rose/config_editor/stack.py
lib/python/rose/config_editor/updater.py
lib/python/rose/config_editor/valuewidget/array/entry.py
lib/python/rose/config_editor/valuewidget/array/logical.py
lib/python/rose/config_editor/valuewidget/array/python_list.py
lib/python/rose/config_editor/valuewidget/array/spaced_list.py
lib/python/rose/gtk/choice.py
lib/python/rose/gtk/dialog.py
lib/python/rose/reporter.py
lib/python/rosie/browser/history.py
lib/python/rosie/suite_id.py
lib/python/rosie/ws_client_cli.py
t/rose-bush/05-cycles-job-fails/suite.rc
t/rose-bush/06-host-port.t
t/rose-host-select/02-localhost.t
t/rose-task-run/30-app-arch-opt-source.t
t/syntax/00-lib.t

Improve test battery robustness for Ubuntu 15.10.

t: improve tests on VM

---

doc/rose-rug-files.html

Minor tweaks and additions. Has been run through tidy which has additionally re-arranged a few lines too.
@benfitzpatrick - please review. I don't think this needs review 2'ing.

Minor revisions to files part of training material (in depth topics I)

---

doc/rose-rug-suites-I.html

doc: fix job submission method example comment

---

bin/rose-task-env
doc/rose-command.html

Improve doc for future duration.

rose task-env: improve --time-delta doc

---

doc/rose-rug-suite-control.html
doc/rose-rug-suites-II.html

@kaday @arjclark please review.

doc: mention `cylc gscan` and other updates

---

lib/html/template/rose-bush/job-entry.html

Ensure that the variable is defined before use.

rose bush: view: no fuzzy time on job entry breaks

---

lib/python/rose/apps/rose_bunch.py
lib/python/rose/reporter.py
t/rose-host-select/02-localhost.t
t/rose-macro/00-null.t
t/rose-macro/12-custom-change.t
t/rose-task-run/08-app-fcm-make.t
t/rose-task-run/09-app-prune-work.log
t/rose-task-run/09-app-prune-work.t
t/rose-task-run/15-app-prune-extglob.t
t/rose-task-run/16-app-prune-point.t
t/rose-task-run/17-app-prune-glob-as-cycle-fmt.t
t/rose-task-run/29-app-prune-extglob-remote.t
t/rose-task-run/31-app-bunch.t
t/rose-task-run/33-app-prune-cycle-format.t

Closes  #1782
@matthewrmshin - please review 1. We can assign review 2 once you're happy with the underlying change being made to rose reporter.

Reporter timestamp

---

CONTRIBUTING.md
lib/python/rose/config.py
t/rose-config/02-self.py

This closes #1821.
@benfitzpatrick  Please review

Config iterator fix

---

lib/python/rose/c3.py

More triangle inheritance tests.

t: rose.c3: more self tests

---

doc/rose-rug-advanced-tutorials-suite-date-time.html

Rose: doc datetime syntax update

---

doc/etc/rose-rug-suite-writing-tutorial/suite.rc.html

@matthewrmshin - please review. Fixes issue highlighted by Mark.
Should only need the one reviewer.

suite writing tutorial: Adjust for consistency.

---

doc/rose-rug-suite-writing-tutorial.html

doc: suite writing tut: updates following feedback

---

lib/python/rose/bush.py
t/rose-bush/11-view-unicode.t

Rose Bush view text (default) failed with code 500 if file contains
Unicode characters. This fixes the problem by outputing the file in
download mode.
@arjclark @benfitzpatrick please review.

rose bush: view text mode: fix 500 on unicode

---

doc/rose-rug-files.html
doc/rose-rug-suite-control.html

@arjclark please review. (1 review enough?)

doc: update usage of some suite commands

---

lib/python/rose/config_editor/ops/group.py
lib/python/rose/config_editor/ops/section.py

This fixes #1774.
@arjclark, @matthewrmshin please review.

rose edit: fix crash on ignore/remove/disable multiple sections

---

lib/python/rose/apps/rose_arch.py
t/rose-task-run/07-app-arch.t
t/rose-task-run/30-app-arch-opt-source.t

This should make it more obvious to users when we have a target with no source from its list of optional sources and/or an optional target with no source.
@benfitzpatrick @kaday please review.

rose_arch: STDERR for target with bad status

---

lib/python/rose/date.py
lib/python/rose/suite_engine_procs/cylc.py

Fix syntax error on recent version of PEP8.
Improve suite host pgrep localhost logic detection.
@benfitzpatrick @kaday please review.

t: fix test failures

---

lib/html/template/rose-bush/cycles.html
lib/html/template/rose-bush/suites.html
lib/python/rose/bush.py
t/rose-bush/09-jobs-fuzzy-time.t

Display fuzzy time again by default for suites and cycles methods. (Broken by #1791.)
Add toggle delta-time button for them as well.

rose bush: fix fuzzy time logic for suites/cycles

---

lib/python/rose/config_editor/menu.py

closes #1709 
@benfitzpatrick Please review

rose edit: show full traceback on macro crash

---

.mailmap
doc/rose-terms-of-use.html

metomi email address update

---

lib/python/rosie/browser/__init__.py
lib/python/rosie/browser/main.py
lib/python/rosie/ws_client.py

closes #1857 
If no sources are selected rosie go now defaults to the first source in the list.

rosie go: no sources crashing gui

---

lib/html/static/css/rose-bush.css
lib/html/static/js/search.js
lib/html/template/rose-bush/search-form.html
lib/html/template/rose-bush/suite-base.html
lib/html/template/rose-bush/view-search.html
lib/html/template/rose-bush/view.html
lib/python/rose/bush.py
t/rose-bush/00-basic.t

Added a search bar enabling users to search log files using either a plain text or regex string.
closes #1111 
@matthewrmshin please review
@benfitzpatrick please review

rose bush: added search feature for viewing log files

---

lib/python/rose/metadata_check.py
t/rose-metadata-check/11-invalid-settings.t

metadata-check: added check for invalid namespace settings.

---

bin/rose-config-diff
doc/rose-command.html
lib/python/rose/config.py
lib/python/rose/config_diff.py
lib/python/rose/opt_parse.py
t/rose-config-diff/00-basic.t

config-diff: added ability to specify opt config keys.

---

lib/python/rose/config_editor/data.py
lib/python/rose/config_editor/main.py

Removed an un-necessary line of code introduced by #1856.

Removed un-necessary metadata refresh.

---

lib/python/rose/bush.py
t/rose-bush/11-view-unicode.t

Fixed bug where Tar'ed files were displayed as plain text.

---

lib/html/static/js/search.js
lib/html/template/rose-bush/search-form.html

Fixes problem where rose bush is not hosted from root.

rose bush: fixed search url

---

doc/rose-rug-getting-started.html

@matthewrmshin - one character correction, think it only needs the one review :grin:

getting started doc: Correct typo.

---

lib/python/rose/config.py
lib/python/rose/macro.py

Fixed env section description not overridable bug.

---

demo/rose-config-edit/demo_meta/app/02-help/meta/rose-meta.conf
demo/rose-config-edit/demo_meta/app/02-help/rose-app.conf
doc/rose-configuration-metadata.html
lib/python/rose/config_editor/data_helper.py
lib/python/rose/config_editor/keywidget.py
lib/python/rose/config_editor/menuwidget.py
lib/python/rose/config_editor/ops/variable.py
lib/python/rose/config_editor/variable.py
lib/python/rose/variable.py

This closes #52.
@oliver-sanders, please review 2.

rose metadata: url: add section or ns root

---

lib/python/rose/config_editor/__init__.py
lib/python/rose/config_editor/menu.py

Closes #1910 
Essentially the same fix applied in #1875 so shouldn't be anything controversial.
@matthewrmshin - please review 1
@oliver-sanders - please review 2

rose edit: handle open gcylc for suite not running.

---

bin/rose-config-edit
doc/css/rose-doc.css
doc/rose-command.html
doc/rose-configuration-metadata.html
doc/rose-configuration.html
doc/rose-rug-advanced-tutorials-trigger.html
lib/python/rose/config_editor/data.py
lib/python/rose/config_editor/main.py
lib/python/rose/macro.py
lib/python/rose/opt_parse.py

rose edit: added option to suppress default version to HEAD warnings

---

lib/html/static/js/search.js
lib/python/rose/bush.py
t/rose-bush/00-basic.t

Fixes a bush which causes the rose bush search feature to fail when hosted on the fcm server.

Fixed bush search url bug.

---

doc/js/rose-doc.js
doc/rose-rug-advanced-tutorials-suite-date-time.html

Fixed a bug whereby sections could be missing from the navigation in the single page version of the documentation.
@matthewrmshin Please Review and add a second if required

rose doc: fixed bug with single page navigation

---

doc/rose-rug-suite-writing-tutorial.html

Closes https://github.com/cylc/cylc/issues/1870
Accompanies https://github.com/cylc/cylc/pull/1914.
@matthewrmshin Please review.

recurrence terminology: repeat -> run

---

lib/python/rose/suite_run.py

Use `tar -cz` to create `log-*.tar.gz` files instead of using Python's `tarfile` and Unix `gzip` command separately to avoid doing double the I/O. Remove the `log-*.tar.gz` file if the command fails.
For reference, the original logic was required to:
* Support old Unix `tar` commands (e.g. default `tar` command on AIX) that do not have the `-z` option.
It is now unlikely that we'll need to do this in the future.
* Avoid Python's `tarfile` very inefficient gzip logic.
@benfitzpatrick @arjclark please review

suite-run: log-*.tar.gz: create by tar command

---

doc/rose-install.html

Point to metomi-vms.
Separate host requirement for Rose Bush from suite run.
@benfitzpatrick please sanity check.

Update installation requirement

---

lib/python/rosie/ws_client.py
lib/python/rosie/ws_client_auth.py

rosie.ws_client: more retries on credential change

---

t/rose-suite-run/14-reload-null.t
t/rose-suite-run/15-reload-rc.t

Modify tests for cylc/cylc#1929. Tests should also work with current cylc master.

t: modify tests for cylc/cylc#1929

---

lib/python/rose/config_processors/fileinstall.py

Delete and update statements are now grouped together, and executed using `executemany`.
We now have a maximum of 3 commits only:
* After tables are created.
* After non-parallel installation are done.
* After parallel installation are done.
@oliver-sanders @arjclark please review, sanity check or reassign.

file install: reduce commits to sqlite database

---

CONTRIBUTING.md
doc/rose-command.html

Add index entry for rose metadata-check

---

doc/rose-rug-advanced-tutorials-clock-triggered.html

Closes #1960 
@oliver-sanders please review. Should only need the one review.

Use printf instead of yes for clock triggered tutorial.

---

lib/python/rosie/suite_id.py

Fixed minor syntax error in #1959.
@matthewrmshin Please review.

Fixed Tests.

---

doc/rose-rug-advanced-tutorials-broadcast.html
doc/rose-rug-advanced-tutorials-suicide.html

These fix a couple of issues I saw when going through a few of the tutorials.

rose documentation: minor advanced tutorial tweaks

---

doc/rose-rug-suite-control.html
lib/python/rose/suite_engine_procs/cylc.py
t/rose-bush/00-basic.t
t/rose-bush/00-basic/suite.rc

Less restriction on what is considered a pattern for sequential files.

Improve rose bush seq log pattern

---

doc/rose-rug-files.html

Fixes an overflowing slide.
@matthewrmshin please review.

rose docs: fix overflowing slide

---

doc/rose-rug-advanced-tutorials-bunch.html
doc/rose-rug-suites-I.html

Some minor documentation updates.

Minor updates.

---

doc/rose-rug-suite-control.html
doc/rose-rug-suites-I.html

Update docs to reflect newer working practice of relying on cylc hooks instead.

Docs: rose hooks advice change

---

lib/python/rose/suite_engine_procs/cylc.py
t/rose-bush/13-jobs-path-in-tar.t

Links contain random files in the tar file. This change fixes the filter
in the logic.

rose bush: jobs list: fix paths in tar links

---

.travis.yml

Gets Travis to re-run any failed tests once. Helps to deal with false positive results.
@matthewrmshin Please Review / Assign

travis: re-run failed tests.

---

lib/python/rose/config_editor/valuewidget/array/spaced_list.py

Closes #1660 
@matthewrmshin Please review.

rose edit: allow newline separators in space-separated list

---

doc/rose-configuration.html
doc/rose-rug-files.html
etc/rose-meta/rose-app-conf/rose-meta.conf
etc/rose-meta/rose-suite-conf/rose-meta.conf
lib/python/rose/config_processors/fileinstall.py
t/rose-app-run/25-file-symlink-plus.t

Check symlink target exists before creating symlink.
Close #1893. @arjclark @oliver-sanders please review.

New file install mode: symlink+

---

doc/rose-rug-config-edit.html

Should be sufficient to close #1220.

Document switch off metadata use case

---

bin/rosie-go
bin/rosie-lookup
doc/rose-command.html
doc/rose-rug-rosie-go.html
lib/html/template/rosie-disco/prefix-index.html
lib/python/rosie/browser/__init__.py
lib/python/rosie/db.py
t/rosie-lookup/00-basic.t

Also correctly support a single quoted string (with space characters) as
a search term.
Close #1681. @oliver-sanders @arjclark please review.

rosie: document search SQL wildcard characters

---

etc/rose.conf.example
lib/python/rose/apps/rose_prune.py
lib/python/rose/suite_engine_procs/cylc.py
t/rose-rug/00-brief-tour.t
t/rose-task-run/39-app-prune-cycle-host.t
t/rose-task-run/39-app-prune-cycle-host/app/pruner/rose-app.conf
t/rose-task-run/39-app-prune-cycle-host/suite.rc

Attempt to prune items only from job hosts of relevant cycles.
Close #1715.

rose_prune: restrict hosts to relevant cycles

---

doc/rose-rug-suites-II.html

Minor updates to suites-II tutorial.

doc: update suites II

---

doc/rose-rug-suites-I.html

@matthewrmshin - fixes the bad slide. Can't find any other cases of this.

Correct from [job submission] to [job] syntax

---

lib/python/rose/config_editor/data.py

rose edit: fix namespaces stealing sort-keys from option sections

---

doc/etc/rose-rug-advanced-tutorials-parameterization-and-jinja2/suite.rc.html
doc/rose-rug-advanced-tutorials-parameterization-and-jinja2.html
doc/rose.html

Add jinja2 + parameterization tutorial.

---

bin/rose-macro
doc/rose-command.html
doc/rose-rug-metadata.html
lib/python/rose/macro.py
lib/python/rose/upgrade.py
t/rose-macro/25-suite-level.t

Close #1766 
`rose macro` now runs default macros on the rose-suite.info file.

run default macros on the rose-suite.info file.

---

lib/html/static/js/rose-bush.js
lib/html/template/rose-bush/taskjobs.html

Add link to un-check all task statuses.

rose bush: taskjobs: uncheck all task statuses link

---

etc/rose-rug-brief-tour/suite.rc
t/rose-rug/00-brief-tour.t

The RUG encourages people to fiddle about with the `my_hello_saturn app config` via rose edit. At present the `my_hello_saturn` task is not in the suite's graph which can be confusing to students trying to find the consequence of the change they have just made.

Doc: Add my_hello_saturn to the RUG suite graphing.

---

t/rose-suite-clean/04-only-3.t

Test was failing on metomi-vms Fedora.

t: rose-suite-clean 04: fix sort order issue

---

lib/html/template/rose-bush/job-entry.html
t/rose-bush/10-jobs-task-status.t
t/rose-task-run/30-app-arch-opt-source.t

Jobs now die with EXIT instead of ERR. (Test broken by cylc/cylc#2218.)

Fix for cylc/cylc#2218

---

doc/rose-configuration.html
doc/rose-rug-stem.html
lib/python/rose/apps/ana_builtin/grepper.py
lib/python/rose/apps/rose_ana.py
t/rose-ana/00-run-basic.t
t/rose-ana/00-run-basic/app/rose_ana_t4/file/lots_of_repetition_1.txt
t/rose-ana/00-run-basic/app/rose_ana_t4/file/lots_of_repetition_2.txt
t/rose-ana/00-run-basic/app/rose_ana_t4/rose-app.conf
t/rose-ana/00-run-basic/suite.rc

Now that the new `rose-ana` has started to see some use a few cases have emerged which could do with addressing...  In particular; it seems desirable to have a way of setting some of the more "global" options from the suite rather than only from within a user's config.... At the same time as this we'll integrate another optional setting that has been requested. 
Closes #2054

Tweaks to rose-ana based on feedback during integration

---

lib/python/rose/gtk/dialog.py

Calculations of width and height of dialog need to factor in the
existence of a scrollbar in the other dimension.

rose config-edit: fix help scroll

---

doc/rose-rug-suites-II.html

Updates the link in Suites-II to point at the cylc suite design guide document.

Update slides to point at cylc suite design guide.

---

doc/rose-rug-suites-I.html

Bizarrely, the multiple inheritance line seems to have slipped a slide. This puts it back where it should be.

Fix inheritance slide.

---

bin/rosie-create
doc/rose-command.html
doc/rose-rosie-advice.html

Should be enough to close #2076.

rosie copy: improve docs on FROM-ID syntax

---

t/rose-suite-log/01-update-cycle.t
t/rose-suite-log/06-archive-star.t

Fix tests broken by cylc/cylc#2314.

Fix tests broken by cylc/cylc#2314

---

doc/rose-rug-advanced-tutorials-rose-stem.html

Two minor tweaks to the rose stem tutorial after running through it.
@scwhitehouse - please review (I imagine this only needs the one review as its a two line doc change)

Tweak rose-stem tutorial

---

doc/rose-rug-advanced-tutorials-broadcast.html

`cylc broadcast` has no `-t` option!

docs: fix cylc broadcast tutorial

---

lib/python/rose/bush.py

Is this what you had in mind - or would you prefer we served all file formats?

recognise html and txt file extensions

---

t/rose-suite-run/19-restart-init-dir-remote.t

Change test configuration to use remote-rose-bin.

---

lib/python/isodatetime/__init__.py
lib/python/isodatetime/data.py
lib/python/isodatetime/parsers.py

See https://github.com/metomi/isodatetime/releases/tag/2017.08.0

Upgrade to isodatetime-2017.08.0

---

doc/rose-rug-advanced-tutorials-clock-triggered.html
doc/rose-rug-suite-writing-tutorial.html
doc/rose-rug-suites-II.html

`clock-triggered` -> `clock-trigger`

docs: fix obsolete clock-triggered setting.

---

lib/python/rose/apps/rose_bunch.py

bunch: fix undefined variable

---

lib/python/rose/apps/rose_ana.py
t/rose-ana/00-run-basic.t

Push import errors to task level in ``rose_ana``

---

lib/python/rose/apps/rose_arch.py

Quick fix for trivial feedback change so @oliver-sanders' PR #2138 could be merged immediately given he is away on leave.

Fix docstring typo from #2138 merge

---

lib/python/rosie/svn_post_commit.py
lib/python/rosie/svn_pre_commit.py
t/rosa-svn-post-commit/00-basic.t
t/rosa-svn-pre-commit/00-basic.t
t/rosie.db/00-query.t

Pre-commit should prevent adding a file at branch level.
Post-commit should no longer die if this happens.

rosa svn-pre-commit: prevent file at branch level

---

.travis.yml
lib/python/rose/suite_engine_proc.py
lib/python/rose/suite_engine_procs/cylc.py
t/rose-suite-clean/01-running.t
t/rose-suite-restart/01-running.t
t/rose-suite-run/00-run-basic.t

Now include information of the location of the contact file and relevant information from within.
Close #2142.

Improve suite still running error message

---

.travis.yml
bin/rose-check-software
bin/rose-make-docs
sphinx/Makefile
sphinx/_static/css/slides-custom.css
sphinx/_static/js/minicylc.js
sphinx/conf.py
sphinx/index.rst
sphinx/tutorial/cylc/introduction.rst
sphinx/tutorial/cylc/runtime/configuration-consolidation/families.rst
sphinx/tutorial/cylc/runtime/configuration-consolidation/index.rst
sphinx/tutorial/cylc/runtime/configuration-consolidation/jinja2.rst
sphinx/tutorial/cylc/runtime/configuration-consolidation/parameters.rst
sphinx/tutorial/cylc/runtime/introduction.rst
sphinx/tutorial/cylc/runtime/runtime-configuration.rst
sphinx/tutorial/cylc/scheduling/datetime-cycling.rst
sphinx/tutorial/cylc/scheduling/further-scheduling.rst
sphinx/tutorial/cylc/scheduling/graphing.rst
sphinx/tutorial/cylc/scheduling/integer-cycling.rst
sphinx/tutorial/rose/applications.rst
sphinx/tutorial/rose/configurations.rst
sphinx/tutorial/rose/metadata.rst
sphinx/tutorial/rose/rosie.rst
sphinx/tutorial/rose/suites.rst
sphinx/tutorial/rose/summary.rst

~**WIP**~
Add a slide functionality using the hieroglyph (http://docs.hieroglyph.io/en/latest/) slide builder.
It makes the markup a bit messy but on the whole seems to be the best option. Extending hieroglyph to implement a nicer interface might be possible but it's probably quite a lot of work.

Rose user guide slides

---

sphinx/developing/index.rst
sphinx/developing/slides.rst

Follow on from #2179 
Quick writeup of the Hieroglyph slide builder.

add developer notes for writing slides

---

t/docs/01-doctest.t
t/lib/bash/test_header
t/rose-app-run/12-file-incr-3.t
t/rose-bush/00-basic.t
t/rose-task-run/40-app-arch-duplicate.t

Remove stray output.
Tidy up suite run time directory.
Fix trap syntax.

Test tidy up

---

lib/python/rose/bush.py

Solution to prevent misuse of rose bush until #2165 is merged / closed.

bush: Only serve files from log dir + suite.rc[.processed]

---

lib/python/rosie/ws_client_auth.py

Closes #2168.
_Note:_ ~~currently for preliminary feedback only, since I am as yet unable to test for functionality due to lack of module availability for ``cherrypy`` & ``sqlaclhemy`` on the present environment installed on the internal RHEL 7 boxes.~~ ~~Awaiting an SRS account to test with.~~ Open for review.

rosie disco: add libsecret password manager

---

sphinx/tutorial/cylc/scheduling/integer-cycling.rst

See https://github.com/cylc/cylc/issues/2707#issuecomment-400938301

docs: fix tutorial solution

---

sphinx/api/configuration/application.rst
sphinx/api/configuration/suite.rst
sphinx/tutorial/rose/furthertopics/optional-configurations.rst

Another setting which has escaped documentation.

document rose-app.conf|opts

---

CONTRIBUTING.md
sphinx/api/configuration/application.rst
sphinx/api/configuration/file-creation.rst
sphinx/api/configuration/metadata.rst
sphinx/api/configuration/rose-configuration-format.rst
sphinx/api/configuration/suite.rst
sphinx/developing/restructuredtext.rst
sphinx/tutorial/cylc/furthertopics/broadcast.rst
sphinx/tutorial/cylc/furthertopics/queues.rst
sphinx/tutorial/rose/applications.rst
sphinx/tutorial/rose/furthertopics/rose-arch.rst
sphinx/tutorial/rose/furthertopics/rose-stem.rst
sphinx/tutorial/rose/furthertopics/trigger.rst
sphinx/tutorial/rose/index.rst

Not a native speaker, so happy to update the pull request with any corrections :-)
Cheers
Bruno

Fix trivial typos in docs

---

lib/python/rose/host_select.py

`socket.gethostbyname_ex(target)` can give different answer to both
`socket.gethostname` and `socket.getfqdn`.
This is the case in my *new* desktop environment where a good long host name is not being recognised as a string for `localhost`.

Add one more way to identify localhost string

---

lib/python/isodatetime/__init__.py
lib/python/isodatetime/data.py
lib/python/isodatetime/run_tests
lib/python/isodatetime/tests.py

Update to isodatetime-2018.09.0. See also cylc/cylc#2773.

Upgrade to isodatetime-2018.09.0

---

sphinx/tutorial/cylc/furthertopics/suicide-triggers.rst

Correct simple error in the suicide trigger documentation.

docs: correct diagram

---

lib/python/rosie/ws_client.py

rosie client: filter out urllib3 warnings

---

lib/python/isodatetime/__init__.py
lib/python/isodatetime/data.py
lib/python/isodatetime/dumpers.py
lib/python/isodatetime/parser_spec.py
lib/python/isodatetime/parsers.py
lib/python/isodatetime/run_tests
lib/python/isodatetime/tests.py
lib/python/isodatetime/timezone.py
lib/python/isodatetime/util.py

Upgrade the bundled isodatetime library.
@sadielbartholomew please sanity check.

Upgrade to isodatetime-2018.11.0

---

lib/python/rose/apps/ana_builtin/grepper.py
lib/python/rose/apps/rose_ana.py
lib/python/rose/apps/rose_ana_v1.py
lib/python/rose/apps/rose_bunch.py
lib/python/rose/bush.py
lib/python/rose/bush_dao.py
lib/python/rose/config_editor/window.py
lib/python/rose/formats/namelist.py
lib/python/rosie/graph.py

I think most typos are harmless, except that I updated a couple of variables that I believe are used for exception/logging. Not sure if some tests are expecting specific values - if so, once Travis points which ones need fixing, will update the commit accordingly :+1:

Batch of typos in a few files (includes exception messages)

---

t/docs/02-tutorial-suites.t

I *think* this aught to do it.

fix flaky test: docs/02

---

lib/python/rose/config_editor/valuewidget/intspin.py

Bug introduced by #2264.
Value change is not being picked up when users input text to the int spin box.
This change should fix.

config-edit: fix int spin box manual edit

---

lib/python/rose/apps/comparisons/output_grepper.py
lib/python/rose/run.py

Hi! Re-synced my repository, and the IDE marked these imports as unused :+1: hoping Travis-CI won't complain about it too.
Cheers

Remove unused imports

---

lib/python/rose/apps/rose_ana.py
t/rose-ana/00-run-basic.t
t/rose-ana/00-run-basic/app/rose_ana_t5/file/kgo.txt
t/rose-ana/00-run-basic/app/rose_ana_t5/file/results.txt
t/rose-ana/00-run-basic/app/rose_ana_t5/rose-app.conf
t/rose-ana/00-run-basic/suite.rc

Implement threading to speed up rose-ana (PR on 2019.01.x)

---

sphinx/api/built-in/rose_prune.rst
sphinx/hyperlinks.rst

doc: rose_prune extglob usage

---

.travis.yml
t/rose-app-run/06-namelist.t

Fix test with unstable sort order.
Improve cylc-flow + fcm download syntax.

[2019.01.x] Fix Travis CI build

---

.travis/now

I think I killed codecov, sorry.

travis: restore coverage

---

sphinx/course/um-ut.rst
sphinx/index.rst
sphinx/tutorial/cylc/scheduling/datetime-cycling.rst
sphinx/tutorial/cylc/scheduling/integer-cycling.rst
sphinx/tutorial/rose/metadata.rst
sphinx/tutorial/rose/suites.rst

Address some of the easier to fix snags in the tutorial material.
Note some of the more involved tasks are covered in #2211 and #2212.
Partly address #2212

docs: tutorial tweaks

---

bin/rose-suite-run
lib/python/rose/config_processors/empy.py
lib/python/rose/config_processors/jinja2.py
t/rose-suite-run/26-jinja2-insert.t
t/rose-suite-run/27-empy-insert.t
t/rose-suite-run/28-rose-site-env.t

Counterpart of #2338 for master branch.

Suite variable dictionary containing all variables inserted in template (master)

---

lib/python/rose/config.py
lib/python/rose/config_tree.py
lib/python/rose/run.py
lib/python/rose/suite_run.py
t/rose-app-run/26-define-overrides.t

Counterpart of #2330 for master branch.

Refactor loading of define overrides - master

---

sphinx/tutorial/cylc/scheduling/datetime-cycling.rst
sphinx/tutorial/cylc/scheduling/integer-cycling.rst
sphinx/tutorial/rose/applications.rst
sphinx/tutorial/rose/metadata.rst

Address some snag points in the tutorial material.

doc: tutorial tweaks

---

sphinx/tutorial/cylc/scheduling/datetime-cycling.rst
sphinx/tutorial/cylc/scheduling/integer-cycling.rst
sphinx/tutorial/rose/applications.rst
sphinx/tutorial/rose/metadata.rst

doc: tutorial tweaks - 2019.01.x

---

setup.cfg
setup.py

@kinow suggested that I could tidy up the setup.py file by creating a setup.cfg which would sit alongside it and contain all non-dynamic content.

Create a setuptools setup.cfg file and use this to tidy up setup.py

---

.travis/now
CHANGES.md
metomi/rose/__init__.py
setup.py

Pre release stuff

---

sphinx/developing/building.rst

Hunspell works for me locally, reference to aspell included for people at other organizations.

adder reference to spill cheeking in the developer/building.rst

---

metomi/rose/apps/rose_arch.py
sphinx/_static/custom.css
sphinx/api/built-in/rose_arch.rst
sphinx/conf.py

fix #2382 
This is a significant re-write of the rose-arch docs, in part an attempt to fix #2382 .
Please feel free to pull apart.

fix rose-arch docs

---

CONTRIBUTING.md
metomi/rose/tests/test_config.py

test_config.py updated to pytest.

Changed unittest to pytest. Added name to contributing.

---

sphinx/glossary.rst
sphinx/hyperlinks.rst
sphinx/tutorial/cylc/furthertopics/index.rst
sphinx/tutorial/cylc/furthertopics/message-triggers.rst

Added tutorial for message triggers.

New tutorial on message triggers for Cylc.

---

lib/python/rose/apps/rose_ana.py
sphinx/tutorial/rose/furthertopics/rose-stem.rst

This is the same change as merged to master (PR2394)[for https://github.com/metomi/rose/pull/2394]

2019.1.x steve ws pr

---

lib/python/rose/suite_engine_procs/cylc.py

Fix bug preventing use of `--host=localhost` in `rose suite-run`

Fix #2390 --host=localhost bug

---

bin/rosie-create

After  a conversation with Adam I attempted to clarify this documentation.

DOCS: Fine tune rosie-create docstring

---

lib/python/rose/config_processors/jinja2.py

Log a warning upon encountering Jinja2 expressions in template variables.
To test:
```console
$ cat *
[scheduling]
initial cycle point = 2000
[[dependencies]]
[[[R1]]]
graph = foo
[runtime]
[[foo]]
$ rose suite-run -l -S 'FOO=range(5)'
[INFO] export CYLC_VERSION=7.8.6
[INFO] export ROSE_ORIG_HOST=vld601
[INFO] export ROSE_SITE=
[INFO] export ROSE_VERSION=2019.01.2-71-g36ead4dcf
[INFO] delete: log/rose-suite-run.conf
[INFO] symlink: rose-conf/20201204T152611-local-install-only.conf <= log/rose-suite-run.conf
[INFO] delete: log/rose-suite-run.version
[INFO] symlink: rose-conf/20201204T152611-local-install-only.version <= log/rose-suite-run.version
[WARN] Template variables will be incompatible with Cylc8/Rose2
[WARN] see: https://cylc.discourse.group/t/cylc8-rose-template-variables-jinja2-su …
```

templatevars: forewarn of cylc8 changes

---

.github/workflows/update_copyright.yml

Plus use new cylc/release-actions actions

GH Actions: prevent update_copyright running on forks

---

metomi/rosie/svn_pre_commit.py
t/rosa-svn-pre-commit/00-basic.t

This is #2421 ported to master. Gives more useful error messages.

(master) Pre-commit hook: Add messages to certain bad changes

---

lib/python/rose/config_processors/jinja2.py

Revert "templatevars: forewarn of cylc8 changes"

---

lib/python/rose/config_processors/fileinstall.py

This test is failing on 2019.01.x:
```
t/rose-app-run/11-file-incr-2.t
```

fileinstall: fix

---

.mailmap
CHANGES.md
CONTRIBUTING.md
metomi/rose/__init__.py

Release PR for Rose (not yet automated).

release: 2.0b1

---

.github/workflows/1_create_release_pr.yml
.github/workflows/2_auto_publish_release.yml
.github/workflows/test.yml
CHANGES.md
t/rosa-svn-post-commit/00-basic.t
t/rosie-lookup/00-basic.t

Close #2462
Demo of stage 1: https://github.com/MetRonnie/rose/pull/1
Don't know if there should be any extra steps for Rose?

Automated release process

---

mypy.ini
setup.py

mypy: fix config

---

metomi/rose/tests/suite_engine_procs/test_cylc.py

Closes #2481 
IMO a 1 reviewer PR.

fix.tests.missing.definition-order

---

.github/workflows/1_create_release_pr.yml

Apply the same fetch-depth patch as for cylc-ui.

actions: fix release action

---

sphinx/tutorial/rose/furthertopics/rose-bunch.rst
sphinx/tutorial/rose/suites.rst

Closes #2499 
Small change to address a small issue
Tests should pass after #2508  merged.

remove refs to rose bush

---

sphinx/Makefile

added nitpicky mode to sphinx options

---

sphinx/tutorial/rose/rosie.rst

Clarify meaning for rosie copy

---

sphinx/api/configuration/suite.rst
sphinx/api/environment-variables.rst
sphinx/tutorial/rose/suites.rst

A couple of changes based on a conversation with @dpmatthews

Small docs changes based on a conversation with Dave

---

.github/workflows/test.yml
setup.cfg

Pygraphviz 1.8 dropped support for Python 3.7

pygraphviz < 1.8

---

sphinx/index.rst

Patch manually applied for 2.0rc1 docs release

docs: edit release candidate message

---

.github/workflows/test.yml
setup.cfg

actions: enable mypy

---

CHANGES.md
rose-version

Pre-release PR
- Updated version strings
- Update `changes.md`
- closed milestone

bump version number 2019.01.7

---

.github/workflows/update_tutorials.yml

GH Actions: update tutorial workflow - more fixes

---

.codecov.yml
.github/dependabot.yml
.github/workflows/2_auto_publish_release.yml
.github/workflows/test.yml
README.md

- Add dependabot.yml to get GH Actions updates PRs
- Run tests on push to `master` and `2.*.x` branches
- Skip style tests on MacOS to speed up
- Fix README badges

Infrastructure stuff

---

.codecov.yml
.github/actions/install-libs/action.yml
.github/dependabot.yml
.github/workflows/1_create_release_pr.yml
.github/workflows/2_auto_publish_release.yml
.github/workflows/shortlog.yml
.github/workflows/test.yml
.github/workflows/test_rsync_test_script.yml
.github/workflows/update_copyright.yml
README.md
metomi/rose/__init__.py

Also install hard-coded cylc-flow 8.0.x and cylc-rose 1.1.x branches instead of master for the tests on the 2.0.x branch

Bump dev version & cherry pick GH Actions stuff

---

t/rose-host-select/02-localhost.t
t/rose-task-run/08-app-fcm-make.t
t/rose-task-run/26-app-fcm-make-new-mode-with-cont.t
t/rose-task-run/35-app-prune-log-on-hosts-sharing-fs.t

Fixes for remote tests not run in CI.

test fixes

---

tox.ini

With #2654 I accidentally opened it against master. Here is the 2.0.x PR

Fix flake8 v6 problem (2.0.x)

---

.github/workflows/2_auto_publish_release.yml

See https://github.com/cylc/release-actions/pull/45

Replace actions/create-release with our version

---

metomi/rose/job_runner.py

* Restore the Rose 2019 concurrency limit of 6.
* Closes #2680
Had to jig the code around a bit to move away from the maximum concurrency model.
For review, please ensure:
* It limits concurrency.
* It still handles errors correctly.
* It runs all the jobs (I think some jobs can be inter-dependent?).
TODO: Need to figure out which branch to put this on => Monday problem.

job runner: limit concurrency

---

metomi/rose/config.py

Mb, put the last PR on the master branch.

flake8 (#2716)

---

sphinx/api/built-in/rose_bunch.rst

Closes https://github.com/metomi/rose/issues/2748
Looks like an error.

fix caps error

---

.github/workflows/test.yml
setup.cfg

Fix MyPy failure on master by only running it with a version of Python we know works.
Additionally:
* Run the linting as a separate fast run/fail test before running other tests.

added a lint task to test workflow

---

.github/workflows/test.yml
metomi/rose/rose.py
metomi/rosie/ws.py
setup.cfg

Replace pkg_resources/setuptools with importlib

---

.github/workflows/test.yml

Spotted in #2783 we are getting the DNS issues here as well
https://github.com/actions/runner-images/issues/8649

GH Actions: patch DNS on MacOS

---

sphinx/conf.py
sphinx/index.rst

Closes #2802 
See https://wxtim.github.io/rose/2.3.0/html/index.html for my version

Fix Forkme banner & Add see rst source

---

CONTRIBUTING.md

Adds my name to the list of contributors.

Update contributing.md with Dimitrios Theodorakis

---

CONTRIBUTING.md

As requested due to my work in #2808.

Add James Frost to contributors

---

.github/workflows/build.yml

Fix the "build" workflow.
See https://github.com/cylc/cylc-flow/commit/5a363642ff1002222b662886c59319b84a62d7c5

build: update location of COPYING file in build package

---

metomi/rose/__init__.py

Workflow: Release stage 2 - auto publish, run: 49
(The auto PR creation failed because we are waiting for https://github.com/actions/runner-images/issues/12648)

Bump dev version
