metomi/rose

doc/rose-rug-advanced-tutorials-rose-stem.html
This fixes the `rose_ana` app example for use with cylc 6 work directory structures.
=> rose doc: update rose stem tutorial for cylc 6 work dirs

lib/python/rose/stem.py
This should fix #1510 - the problem is the "rose-stem" in the branch (and thus by default the working copy) name, unfortunately Python's string.replace method doesn't seem to have a "work from the right hand side of the string" option, so I've replaced it with a regular expression.
@matthewrmshin would you mind reviewing when you get chance?
=> Rose stem in branch name

etc/rose-meta/rose-suite-info/rose-meta.conf
Removes the accidentally introduced "opts" entry from rose suite-info metadata.
=> rose-suite-info metadata: Remove incorrect opts entry.

t/rosa-svn-post-commit/01-mail-passwd.t, t/rose-app-run/09-file-incr-0.t, t/rose-app-run/11-file-incr-2.t, t/rose-app-run/12-file-incr-3.t, t/rose-app-run/14-file-source-optional.t, t/rose-cli-bash-completion/00-static.t, t/rose-host-select/01-timeout.t, t/rose-metadata-graph/01-data.t, t/rose-metadata-graph/02-just-metadata.t, t/rose-rug-simple/00-normal.t, t/rose-suite-clean/04-only-3.t, t/rose-suite-clean/06-only-5.t, t/rose-suite-log/02-update-force.t, t/rose-suite-log/06-archive-star.t, t/rose-suite-run/10-import-1.t, t/rose-suite-run/11-import-2.t, t/rose-suite-run/17-install-overlap.t, t/rose-task-run/07-app-arch.t
This fixes a number of (fake) test failures when running on machines with different `LANG`
settings.
N.B. I didn't want to enforce `LANG=C` at the whole test-battery level, as it is an
antiquated setting.
=> rose test-battery: enforce LANG=C for all 'sort' commands

t/lib/bash/test_header
This fixes a bug in the file comparison failure reporting for `rose test-battery`.
=> rose test-battery: fix debug output for stdin cmp

t/lib/bash/test_header, t/rosie.db/00-query.t
This fixes a test problem with slightly differing (but functionally equal) output from later
versions of SQLAlchemy. This introduces a 'either this content or this content or this content'
kind of test.
=> rose test-battery: add file_cmp_any test, fix sqlalchemy output variation

t/rose-suite-run/12-run-dir-root.t
This fixes a failure in `t/rose-suite-run/12-run-dir-root.t` when `TMPDIR` is not set.
@kaday, please review.
=> Fix test fail on unset TMPDIR

etc/rose-bash-completion, t/rose-cli-bash-completion/00-static.t
This fixes the use of getent for user names - getent alias can return differently formatted results
on different systems.
=> rose bash completion: fix use of getent for user names

t/rose-app-run/05-file.t, t/rose-suite-clean/03-only-2.t
This fixes some timing-dependent ordering in two of our test-battery tests.
=> rose test-battery: fix arbitrarily-ordered test output

lib/python/rose/config_editor/menuwidget.py
When a macro created a warning for a variable, the variable menu was unlaunchable.
This was due to a '/' in the generated warning name, which confused the menu
uimanager. This had been fixed for variable macro errors before, in exactly the same
way (a few lines above).
To recreate the problem, create an app with the following `rose-app.conf`:
```
[env]
FOO=bar
```
and a `meta` directory with a blank `rose-meta.conf`. The meta directory should have
a `lib/python/macros/` subdirectory with an empty `__init__.py` and a file `warning.py`
that looks like this:
```python
import rose.macro
class FooWarning(rose.macro.MacroBase):
def validate(self, config, meta_config):
self.add_report("env", "FOO", "bar", "Is horrible?", is_warning=True)
return self.reports
```
After running the macro for the …
=> rose edit: fix variable menu when it has a macro warning.

lib/python/rosie/browser/main.py, lib/python/rosie/suite_id.py
The `View Web` popup menu item for a suite is now only sensitive if
`[rosie-id]prefix-web.*` is defined for the *prefix* of the suite.
Fix #1489.
=> rosie go: sensitive web browser menu item

lib/python/rose/job_runner.py, t/rose-app-run/06-namelist.t, t/rose-app-run/15-file-permission.t
Should fix #1526. Failed jobs are now properly recorded and reported. Not obvious how to write a dedicated automated test.
=> rose.job_runner: correctly handle exceptions

doc/rose-configuration.html, doc/rose-rug-task-run.html, lib/python/rose/apps/rose_prune.py, t/rose-task-run/15-app-prune-extglob.t, t/rose-task-run/15-app-prune-extglob/app/creator/rose-app.conf, t/rose-task-run/15-app-prune-extglob/app/pruner/rose-app.conf, t/rose-task-run/15-app-prune-extglob/suite.rc
This ensures that `bash -O extglob` is used to run all pruning commands.
Resolve bullet point 3 of #1491. Close #1420.
=> rose_prune: prune command uses `bash -O extglob`

etc/rose.conf.example
This fixes a mistake in the example documentation (the names are not
actually consistent with other option names).
=> rose.conf example: fix underscore/dash mixup

lib/python/rose/config_editor/menu.py, lib/python/rose/config_editor/panelwidget/filesystem.py, lib/python/rose/gtk/dialog.py
This catches an exception thrown when a bad `[external]fs_browser` setting is defined and a file
browser is launched through `rose edit`.
=> rose edit: catch fs browser launch exception

lib/python/rose/config_editor/menu.py
`rose edit` did not report any failures or errors from an internal launch of `rose metadata-graph`.
Failures can be caused by:
* apps with no metadata
* invalid site/user `[external]image_viewer` configuration
=> rose edit: report errors from metadata-graph

t/rose-app-run/05-file.t
=> rose test-battery: fix remaining unsorted rose-app-run output

t/lib/bash/test_header, t/rose-metadata-graph/01-data.t, t/rose-metadata-graph/02-just-metadata.t, t/rose-metadata-graph/test_header_extra
This fixes the tests for rose metadata-graph under newer (quite different) graphviz output.
The principal differences of the newer format are:
* difference in order of properties, which now have to be sorted by us
* breaking properties across multiple lines
=> rose test-battery: fix metadata-graph in new graphviz output 

lib/python/rose/config_editor/ops/section.py
This fixes #1545. The hover-over text for added or removed section was the opposite of what we wanted!
=> rose edit: fix incorrect added-section description

bin/rose-config, doc/rose-command.html
Option is no longer supported by the logic.
Close #1546.
=> rose config: remove --has from docs

doc/rose-variables.html
This fixes some incorrect links in the variables documentation.
=> documentation: fix wrong command links in rose-variables.html

doc/rose-api.html, lib/python/rose/upgrade.py, t/rose-app-upgrade/08-category-is-package.t
This fixes #1554. The root cause of this problem is that different `versions.py` files in different
metadata categories can attempt to import exactly the same named submodules.
For example, both `versions.py` files might look like this:
```
from versionX_Y import * 
from versionY_Z import *
```
where `X`, `Y`, `Z` are some common tags between the two categories.
Python will attempt to use the first `versionX_Y` module it imports for both categories.
This happens in a `rose edit` suite editing context.
This fix allows a workaround for the problem by allowing the `versions.py` parent directory
to look like a Python package (add an `__init__.py`). The `__init__.py` must `import versions`
at least in the way I've currently implemented it.
The `versions.py` file can then look like this:
``` …
```
=> rose edit, rose app-upgrade: allow category packages

demo/rose-config-edit/demo_meta/app/12-file/rose-app.conf, lib/python/rose/config_editor/data_helper.py
This fixes #1527.
It fixes the example given in that issue, and the non-optimal hover-over behaviour for the related `file:directory/` problem.
=> rose edit: fix blank ns for trailing slash section

etc/rose-conf.lang
This fixes the gedit syntax highlighting, at least for Ubuntu 14.04 and gedit 3.10.
@dpmatthews, please review.
=> Alter instructions for gedit 3 syntax highlighting

lib/python/rose/suite_run.py
`rose suite-run --restart` should now export `CYLC_VERSION` to the value used to originally start
the suite.
(N.B. The new `rose suite-restart` command should do this already.)
=> rose.suite_run: use orig cylc version on restart

lib/python/rose/variable.py, t/rose-macro/05-value-values-check.t, t/rose.variable/01-array-split.t, t/rose.variable/t_array_split.py
The main intention of this change is to ensure that escape characters
are removed after parsing the value.
The implementation now uses Python's standard `shlex` module, which
allows our logic to be simplified.
Fix #1363.
=> rose.variable.array_split: fix left behind escape

lib/python/rosie/svn_pre_commit.py, lib/python/rosie/usertools/ldaptool.py, lib/python/rosie/usertools/passwdtool.py, t/rosa-svn-pre-commit/02-passwd.t
On suite copy, a bad user ID in `owner` or `access-list` was not being
rejected by the Rosie pre-commit hook. This change fixes the problem.
Fix #1556.
=> rosa svn-pre-commit: fix copy with bad owner

t/rose-host-select/01-timeout.t
For some systems, the host report ordering can sometimes be different.
=> rose test-battery: fix flakey host-select test

lib/python/rose/apps/comparisons/output_grepper.py, lib/python/rose/apps/comparisons/within.py
A user has said it would be nice if, where numbers differ, the values were printed. This change alters the "Within" comparison so that if two values are compared, it prints the numerical values if they differ as well as a percentage difference. If two lists of values are compared only the percentage difference is printed (as before), but now together with the position in the list of that value. So you can now tell that, for example, the fourth value in the list was the first different one and it was different by 6%, say.
This also fixes a bug where a test was meant to be on wallclock time, but it was accidentally testing CPU time instead.
=> Improve output from rose-ana and fix a bug

lib/html/rose-bush/jobs.html, lib/python/rose/bush.py
Only hide the *Display Options* form if all options are set as defaults.
Close #1110 and #1162.
=> rose bush: jobs: hide options only if default

t/rose-task-run/15-app-prune-extglob/suite.rc
On some platforms, this test sometimes fails due to reporting an extra pruning of
`share/data/20150101T0000Z`.
The current test suite has an undefined order of precedence for the tasks - changing
this seems to fix it.
=> rose test-battery: increase reliability of task-run extglob test.

doc/rose-rug-suites-I.html
NIWA have moved their ECOX suite image. This links against the image in the cylc user guide which should be a bit more stable.
@benfitzpatrick - please review.
=> Fix link for image of ECOX.

lib/python/rose/suite_hook.py, t/rose-suite-hook/04-mail-bad.t, t/rose-suite-hook/04-mail-bad/suite.rc
Particular (mis?)configurations of SMTP programs can cause `rose suite-hook --mail --shutdown`
to crash at the `--mail` stage before it can issue the suite shutdown command. This can result
in the suite hanging around, which is not nice!
=> rose suite-hook: --shutdown even if --mail fails

lib/python/rosie/ws_client_auth.py
Move gpg-agent above GnomeKeyring (as gpg-agent is more readily available).
=> rosie.ws_client_auth: swap keyring agent order

bin/rose-host-select, doc/rose-command.html, etc/rose.conf.example, lib/python/rose/host_select.py, lib/python/rose/opt_parse.py, t/rose-host-select/01-timeout.t, t/rose-host-select/01-timeout/bin/mock-ssh, t/rose-host-select/01-timeout/etc/rose.conf
Reinstate timeout logic. Kill SSH commands if they take too long to complete - treat hosts with killed SSH commands as dead hosts.
Run SSH commands in serial (to reduce system load) when selecting by random with no thresholds.
=> rose host-select: reinstate timeout and improve random selection logic

lib/python/rose/suite_engine_procs/cylc.py, t/rose-suite-run/20-pgrep-conflict.t, t/rose-suite-run/20-pgrep-conflict/suite.rc
`rose suite-run` currently does a `pgrep` for suite processes to detect whether
the suite is already running. This `pgrep` can incorrectly match "cylc-run foo-bar"
when looking for "cylc-run bar".
This change fixes the `pgrep` pattern.
=> rose suite-run: allow suite 'bar' when suite 'foo-bar' is also running

bin/rose-config-diff, doc/rose-command.html, etc/rose.conf.example, lib/python/rose/__init__.py, lib/python/rose/config_diff.py, lib/python/rose/opt_parse.py, lib/python/rose/popen.py, t/rose-config-diff/00-basic.t, t/rose-config-diff/test_header
This produces diffs between two config files, altered to include
selected metadata as comment text. This closes #1293.
This is derived from the original work done by Craig
Maclachlan (@craigmaclachlan).
=> rose config-diff: metadata-annotated config diffs.

bin/rose-suite-shutdown
Missed adding the documentation addition from #1573 to the CLI help.
Verified as OK by @kaday at my desk.
=> rose suite-shutdown: Add missing line to cli help.

t/lib/bash/test_header, t/rose-config/04-meta.t, t/rose-suite-hook/03-mail.t, t/rose-suite-hook/04-mail-bad.t
This fixes the clash between `03-mail.t` and `04-mail-bad.t`.
The `04-mail-bad.t` test now uses an entirely fake SMTP server
on a different set of possible ports.
The underlying problem was that `03-mail.t` had hardcoded itself
to port 8025, which may explain the odd failures it had now and
then in past test battery runs.
=> rose test-battery: fix suite-hook smtp clash

t/rose-ana/00-run-basic.t, t/rose-ana/00-run-basic/suite.rc
For some reason, the event hooks are causing the suite to hang. Removing
them allow the test to robustly pass without hanging.
@scwhitehouse please review.
=> t/rose-ana/00: fix hang up

lib/python/rosie/browser/__init__.py, lib/python/rosie/browser/main.py, lib/python/rosie/browser/suite.py
On issuing the command to create a new suite:
* If a single data source is selected, it will use the selected data
source as the prefix of the new suite.
* If multiple data sources are selected, it will display a dialog box
to allow the user to select a prefix from one of the data sources.
The title of the new suite info dialog will now display the prefix (for
a new create) or the from-id (for a copy).
@arjclark please review. Fix #1598.
=> rosie go: allow prefix selection on suite create

lib/python/rose/config_editor/pagewidget/__init__.py
```lib/python/rose/config_editor/pagewidget/__init__.py``` tries to import  ```chooser```, which was deleted by 20e2dc78a24ff034bdbf76874574c20aea613863
(although maybe I've missed something as evidently this didn't break your Rose installation?)
=> Removed an obsolete import.

doc/rose-rug-suite-writing-tutorial.html
This fixes the link to google maps, which has changed URL formats.
=> rose doc: fix suite writing tutorial google maps link

lib/python/rose/env.py, t/rose.env/00-export.t, t/rose.env/test_header
E.g. This fixes `rose task-run` reporting `export PATH=...` twice.
=> rose.env.env_export: report 1st time and on change

doc/rose-rug-task-run.html, doc/rose-variables.html, etc/rose-meta/fcm_make/HEAD/rose-meta.conf, lib/python/rose/apps/fcm_make.py, lib/python/rose/task_env.py, t/rose-task-run/08-app-fcm-make.t, t/rose-task-run/18-app-fcm-make-ctx-name.t, t/rose-task-run/18-app-fcm-make-ctx-name/app/make/file/fcm-make.cfg, t/rose-task-run/18-app-fcm-make-ctx-name/app/make/file/src/hello.f90, t/rose-task-run/18-app-fcm-make-ctx-name/app/make/rose-app.conf, t/rose-task-run/18-app-fcm-make-ctx-name/app/run/rose-app.conf, t/rose-task-run/18-app-fcm-make-ctx-name/suite.rc, t/rose-task-run/19-app-fcm-make-ctx-name-with-share, t/rose-task-run/19-app-fcm-make-ctx-name-with-share.t
Add `mirror.target=` to `fcm make` argument list as extra configuration, instead of relying on environment variables. This should work as long as we are on FCM 2014-03 or above.
Use `-n 2` option of `fcm make` where relevant - this allows the continuation make to be in the same physical location.
New functionality dependent on metomi/fcm#188, but change should otherwise be backward compatible.
=> fcm make 2: improve support

lib/python/rose/host_select.py
It was not doing a proper floating point comparison.
=> rose host-select: fix incorrect threshold logic

bin/rose-app-upgrade, bin/rose-macro, doc/rose-command.html, doc/rose-configuration.html, lib/python/rose/config.py, lib/python/rose/config_editor/data.py, lib/python/rose/macro.py, lib/python/rose/metadata_check.py, lib/python/rose/upgrade.py, t/rose-app-upgrade/09-opt.t, t/rose-app-upgrade/test_header, t/rose-cli-bash-completion/00-static.t, t/rose-macro/18-opt-conf-check.t, t/rose-macro/19-opt-conf-change-add.t, t/rose-macro/20-opt-conf-change-modify.t, t/rose-macro/21-opt-conf-change-remove.t, t/rose-macro/test_header
We can now handle validation and macro transformation of
optional configurations in rose macro and rose app-upgrade.
The commands now support `-O` and `--opt-conf-key` options.
The old `output_dir` option has been changed to use `-o` rather
than `-O`.
This closes #1334.
Validation is easy.
Transforms are hard. It is difficult to know what to apply
where. It currently works like this:
* add setting in macro => add settings to the main configuration, unless
their parent section only exists in an optional configuration
* modify setting in macro => modify setting only in the last applied
configuration containing that setting (so e.g. in the optional
configuration rather than the main one, which would get overwritten).
* remove setting in macro => remove setting from all configurations
In the …
=>  rose macro, app-upgrade: handle opt confs.

t/rose-app-run/12-file-incr-3.t
Using `bash -l` may not work if temp dir gets removed at end of session.
=> t: fix logic to get temp dir in job host

doc/rose-rug-advanced-tutorials-polling.html, doc/rose-rug-task-run.html
Update to documentation to reflect that the code supports ISO8601 date-time format
=> rose doc: update [poll] delays to ISO8601

doc/rose-install.html, etc/rose.conf.example
Move sections around so:
* user stuffs are nearer the top.
* easier stuffs are nearer the top.
* Rosie client configuration and Rosie server configuration are in separate sections.
Discuss whether it is possible/necessary to set up Rose Bush and/or
Rosie web service.
Updated `rose.conf.example` file so that `[section]` names appear at the top (as well as at the bottom). It looks a bit strange, but is syntax-OK, and users are less likely to get it wrong.
=> install doc: more discussion on admin stuffs

lib/python/rose/config_editor/valuewidget/valuehints.py
This fixes a traceback for a `value-hints` widget:
```
File "/opt/rose/lib/python/rose/config_editor/variable.py", line 73, in __init__
self.generate_valuewidget(variable)
File "/opt/rose/lib/python/rose/config_editor/variable.py", line 197, in generate_valuewidget
hook_object, custom_arg)
TypeError: __init__() takes exactly 5 arguments (6 given)
```
@kaday, please review.
=> rose edit: fix value hints widget initialisation

lib/python/rose/config_editor/valuewidget/source.py
Ensure that essential modules are imported. Close #1627.
@arjclark please review.
=> rose config-edit: source widget: import essentials

lib/python/rosie/browser/main.py, lib/python/rosie/ws_client.py, lib/python/rosie/ws_client_cli.py, t/rosie-hello/00-null.t, t/rosie-hello/test_header
Return a friendlier error message when no [rosie-id] settings are defined in
the site/user configuration.
Close #1634.
=> rosie.ws_client: improve diagnostics on null conf

lib/python/rose/config_editor/valuewidget/array/entry.py, lib/python/rose/config_editor/valuewidget/array/mixed.py, lib/python/rose/config_editor/valuewidget/array/python_list.py, lib/python/rose/config_editor/valuewidget/array/row.py, lib/python/rose/config_editor/valuewidget/array/spaced_list.py
This fixes an edge case where an array widget causes a crash on error checking when
the variable has a null value but the widget has a null character string. This is allowed for
compulsory character type variables.
The traceback can be reproduced via having a `rose-app.conf` file that looks like this:
```ini
[env]
FOO=
```
and a `rose-meta.conf` file that looks like this:
```ini
[env=FOO]
compulsory=true
fail-if=true
length=:
type=character
```
Open in `rose edit`, navigate to the environment, click to add (the first) array element, and then click "Run all validators" in the toolbar. This will produce a traceback that looks like this:
```
File "/opt/rose/lib/python/rose/gtk/util.py", line 294, in <lambda>
lambda b: function())
File …
```
=> rose edit: array widgets: protect against unsaved null text

lib/python/rose/bush.py
If a user has a bad entry in their rose-suite.info file for one of their suites it prevents rose bush from being able to list *any* of them in the suites view. Similarly, you cannot view that specific suite either.
This change captures exceptions thrown by bad config entries in rose-suite.info files.
Example file for testing:
```
owner=me
project=some project
title=some title
THIS BREAKS ROSE BUSH
```
=> rose bush: fix handling of bad rose-suite.info files

lib/python/rose/config.py, lib/python/rose/config_editor/__init__.py, lib/python/rose/config_editor/main.py, lib/python/rose/config_editor/menu.py, lib/python/rose/config_editor/nav_controller.py, lib/python/rose/config_editor/ops/group.py, lib/python/rose/config_editor/ops/section.py, lib/python/rose/config_editor/ops/variable.py, lib/python/rose/config_editor/stack.py, lib/python/rose/config_editor/updater.py
This change speeds up applying large macro changes in `rose edit`.
There are two parts to this:
* Don't store an 'undo' for each operation - instead, store a config diff object (from #1334) for the whole macro change set. This closes #836.
* Consolidate updating so that it is only done at the end of the whole change set, with each namespace only being updated once.
There is a move of code from menu.py to 'apply_diff' in group.py, which largely preserves the previous logic. The changes are now dependent on the actual diff from the original config, instead of being awkwardly based around the macro reports as before. This is good as a macro may lie about its reports!
498509c and 62869f4 fix a bug where variable errors weren't always being removed if their section was ignored.
=> rose edit: speed up macro changes

lib/python/rose/config_dump.py, t/rose-config-dump/03-prettyprint.t
This fixes an inconsistency (bug) in rose config-dump, where it would tidy
up metadata files as long as they weren't in the current directory.
=> rose config-dump: don't prettify metadata

bin/rose-rug-brief-tour, lib/python/rose/suite_run.py, t/rose-suite-run/02-install.t
Improve `rsync` commands in logic.
* The `rose rug-brief-tour` command was far too complicated. All it does is a local copy.
* For `rose suite-run`,
use `rsync` command's `--exclude=PATTERN` options to exclude items from source,
instead of listing items in the source directory.
Added a file with colon in its name to the install test.
=> rose suite-run: install: handle colon in file name

doc/rose-command.html
The notes are no longer required now that we fully support ISO-8601 date
time cycle points.
=> doc: rose task-env: remove cycle point notes

lib/python/rose/suite_run.py, t/rose-suite-run/23-reload-host.t, t/rose-suite-run/23-reload-host/suite.rc
It was previously failing if a new host is added to the suite.
Fix #1653.
=> rose suite-run --reload: new host, fixed

bin/rosie-graph, doc/rose-command.html, lib/python/rose/metadata_graph.py, lib/python/rose/opt_parse.py, lib/python/rosie/graph.py, t/rosie-graph/00-basic.t, t/rosie-graph/test_header, t/rosie-graph/test_header_extra
The proliferation of suites and the copy-suite working practice can make it difficult
to keep track of which suites are related, and how. This command creates a graph
of suite ancestry.
The internals are similar to `rose metadata-graph` (but simpler).
=> rosie graph: plot suite ancestry

lib/python/rose/config_diff.py, t/rose-config-diff/00-basic.t
This fixes #1672.
@matthewrmshin, please review 1+2.
=> rose config-diff: fix input path with no dirname

lib/python/rosie/browser/main.py
This fixes #1665.
@arjclark, please review 1.
@kaday, please review 2.
=> rosie go: fix crash on invalid search

lib/python/rose/config_editor/page.py
This fixes #1656.
@kaday, please review 1.
@matthewrmshin, please review 2.
=> rose edit: fix unnamed variable close page crash

CONTRIBUTING.md, lib/python/rosie/ws_client_auth.py
When a user first starts `rosie go` it asks to authenticate to the various servers. It requests this using the site prefix, e.g. `e`, which isn't necessarily meaningful to new users.
Instead of using the site prefix prompt users with the full URL, e.g. `https://example.com/rosie`. This way users can easily identify what they're being asked to connect to, and can go to that URL if necessary to learn more about it.
=> Use hostname for authentication prompts

lib/html/rose-bush/broadcast-events.html
To avoid hanging up the browser.
I have tested this in my environment with a suite with thousands of broadcast events. It is easy on both the server (no complex queries) and the client (no complex rendering). Obviously, it is not as nicely laid out as before, but should display the information much quicker.
Close #1671.
=> rose bush: broadcast-events: use simple log style

CONTRIBUTING.md, lib/python/rose/gtk/splash.py
Fix for "IOError [Errno32] Broken pipe" which is seen frequently on puma without this change. Issue occurs when launching rosie go. 
Ros did quite a lot of testing, including using the exact same versions of python modules as at the MetO, but was unable to track down the cause of the error.
=> Rosie go: Add try except to catch broken pipe error on puma.

doc/rose-variables.html
Adds `ROSE_TASK_LOG_DIR` to the documentation (currently missing).
=> Document ROSE_TASK_LOG_DIR

lib/python/rose/suite_run.py
Python 2's `tarfile.TarFile.close()` is sometimes inadequate for our large files.
This can cause a fatal problem in the `gzip` call on the next line ('log.XXX.tar not found').
@matthewrmshin, please review 1.
=> rose suite-run: fix occasional tarfile crash

etc/rose-conf-mode.el
Prevent warning from emacs:
http://stackoverflow.com/questions/24779041/disable-warning-about-emacs-d-in-load-path
=> Emacs rose-conf-mode: correct installation instructions & highlight rose-suite.info files

bin/rose-app-run, bin/rose-suite-run, doc/rose-command.html, doc/rose-configuration.html, doc/rose-variables.html, lib/python/rose/config.py, lib/python/rose/config_tree.py, t/rose-app-run/22-opt-conf-key-missing.t
Allow missing optional configuration keys via CLI option and
environment variable.
Close #1694.
=> rose task-run: allow -O (key) syntax

doc/rose-command.html, doc/rose-configuration-metadata.html
Typo corrected and documentation on `copy-mode` added.
=> rosie: rose-suite.info metadata doc update

lib/python/rose/formats/namelist.py, t/rose-macro/22-repeats.t
This fixes a bug in namelist repeat syntax parsing.
@matthewrmshin, please review. No 2-review necessary, I think.
=> rose.namelist: fix parsing of blank value repeats

lib/python/rose/run_source_vc.py, lib/python/rosie/suite_id.py
Call to `svn diff` may hang if user has an alternate diff command
configured that hangs. This change should force `svn diff` to use its
internal diff logic.
Fix #1717.
=> rose suite-run: fix hang up of svn diff

doc/rose-rug-metadata.html
=> rose doc: typo values

lib/python/rosie/vc.py, t/rosie-create/01-suite-info-meta.t
It looks like the use of a temporary handle for the info file is not
optimal, as some editors cannot handle modifying the file in place.
This problem is probably introduced by #1713.
@benfitzpatrick @arjclark please review.
=> rosie create: fix editor problem

bin/rose-suite-hook, doc/rose-command.html, lib/python/rose/opt_parse.py, lib/python/rose/suite_hook.py, t/rose-suite-hook/01-job-host/suite.rc, t/rose-suite-hook/05-job-logs-retrieved.t, t/rose-suite-hook/05-job-logs-retrieved/suite.rc, t/rose-suite-log/00-update-task/suite.rc, t/rose-suite-log/01-update-cycle/suite.rc, t/rose-suite-log/02-update-force/suite.rc
Recent version of cylc, e.g. 6.7.1, has the ability to efficiently
retrieve remote job logs. The equivalent functionality in
`rose suite-hook` should now be considered unnecessary. This change
modifies the behaviour so that the functionality will not be carried out
unless the new `--retrieve-job-logs` option is specified.
See also #1731. @arjclark @kaday please review.
=> rose suite-hook: --retrieve-job-logs

demo/rose-config-edit/demo_meta/app/01-types/meta/rose-meta.conf, demo/rose-config-edit/demo_meta/app/01-types/rose-app.conf, doc/rose-configuration-metadata.html, lib/python/rose/__init__.py, lib/python/rose/config_editor/valuewidget/__init__.py, lib/python/rose/config_editor/valuewidget/booltoggle.py, lib/python/rose/meta_type.py, t/rose-macro/01-value-type-check-ok.t
Adds a python boolean metadata type.
Motivated by:
* frequent using of jinja2 switches in suite.conf files and desire for suitable metadata type for that
* desire for python boolean as part of #1696 
@kaday - please review 1
@benfitzpatrick - please review 2
=> meta types: Add python_boolean meta type

bin/rose-suite-hook, bin/rose-suite-restart, doc/rose-command.html, doc/rose-rug-files.html, doc/rose-rug-getting-started.html, doc/rose-rug-introduction.html, doc/rose-rug-quiz.html, doc/rose-rug-suites-I.html, doc/rose-rug-suites-II.html
Minor documentation changes to correct or update some slides that have been annoying me.
Of note:
* Correcting capitalisation of cylc in line with how used in cylc user guide
* Add mention of rosie graph to suite copy/branch slides
@kaday - please review (feel free to add a 2nd reviewer if you think that's appropriate).
=> Documentation tweaks/updates.

t/rose-suite-log/00-update-task.t, t/rose-suite-log/01-update-cycle.t, t/rose-task-run/05-app-prune-compat.t, t/rose-task-run/06-app-prune-iso.t, t/rose-task-run/12-app-prune-integer.t, t/rose-task-run/14-app-prune-remove.t, t/rose-task-run/31-app-bunch.t
Retry delays in cylc `global.rc` can cause some tests to fail. This
change allows the tests to run in purer form without cylc `global.rc`
settings.
This change also ensures that the new rose_bunch test is able to tidy up
the suite. The NAME variable (suite name) was modified before it is
supplied to the `rose suite-clean` command.
=> t: improve robustness

lib/python/rose/apps/fcm_make.py, t/rose-task-run/24-app-fcm-make-fast.t
When using a fast location, the logic creates a temporary directory on
the fast location. This is rsync to the final destination on exit of the
`fcm make` command. The old did take into account permission mode of the
temporary directory back to the final destination, but the logic was
insufficient, as the directory permission mode is overridden by
`rsync -a`. The new logic fixes this by inquiring the permission mode of
the normally created directory at the final destination, then run the
`rsync -a` command, before setting the permission mode of the directory
to the the value of that of the normally created directory.
=> fcm_make built-in: fix fast location perm mode

lib/python/rose/apps/rose_arch.py, lib/python/rose/config.py, t/rose-config/03-syntax-error.t, t/rose-task-run/07-app-arch/app/archive/rose-app.conf
Apply to sections with schemes, e.g. `[namelist:foo{bar}(24)]`
Check syntax of braces `{}` and brackets `()`. Allow only:
* 0 or 1 pair of each.
* braces before brackets.
E.g. an extra close bracket in the section value will result in an exception like:
```
rose.config.ConfigSyntaxError: /home/matt/foo/opt/rose-app-ouch.conf(32): unexpected character or end of value
[namelist:teddy{bad}}]
^
```
=> rose.config: check section syntax

lib/html/template/rose-bush/job-entry.html
Don't bother truncating task name. A long name will automatically move itself down any way.
=> rose bush: job entry: don't truncate entry name

lib/python/rose/suite_engine_procs/cylc.py
Filtering jobs by status in rose bush (2015.11.1) is currently broken. This fixes the query so it will now work.
Can be tested by viewing suite results mot-aa834 in my area and filtering jobs using each checkbutton.
@matthewrmshin please review 1
@kaday please review 2
=> rose bush: Fix sqlite query for filtering jobs by status.

lib/python/rose/host_select.py, t/rose-host-select/02-localhost.t
This was causing test failures in Ubuntu 15.10.
The fix should allow it to identify more IP addresses associated with
the localhost.
=> rose host-select: a localhost str may have 1+ IP

lib/python/rose/suite_engine_procs/cylc.py, t/rose-bush/00-basic.t
Previously, it was failing if it was unable to find `log/job/` in the suite
running directory.
=> rose bush: jobs: no frill display of cylc-suite.db

t/rosie-create/00-basic.t
Caused by modifying a file to be comitted with a random number that may
be exactly the same as the original file - which caused the test to fail
with a 1 in 10 chance.
@arjclark please review. (I don't think we need a 2nd.)
=> t: rosie-create 00: fix random failure

doc/rose-rug-task-run.html, lib/python/rose/apps/rose_arch.py, t/rose-task-run/30-app-arch-opt-source.t, t/rose-task-run/30-app-arch-opt-source/app/archive1/rose-app.conf
New syntax to indicate a target may have no source.
New status for target with no source.
doc: optional target and more on rose_arch output.
See also #1707 and #1708.
=> rose_arch: optional target

lib/python/rosie/browser/__init__.py, lib/python/rosie/browser/main.py, lib/python/rosie/ws_client.py, lib/python/rosie/ws_client_auth.py, lib/python/rosie/ws_client_cli.py
This handles an error thrown by `gnomekeyring` in the rosie auth layer when the keyring is locked.
In current master, a nasty traceback is thrown. The new behaviour is to disable prefixes before use (and notify the user about it) if a `hello` call fails. This applies to other auth failures as well.
The `gnomekeyring` situation can be replicated by launching `seahorse` and locking the `login` keyring. Other auth failures can be replicated by setting the wrong username or password.
@matthewrmshin, please review 1.
=> rosie.ws_client_auth: handle keyring denied, disable bad prefixes

lib/python/rose/apps/rose_arch.py, t/rose-task-run/07-app-arch.t
When a source glob fails to return a valid file, return the full path of
the glob including the source prefix in the exception message.
Problem reported by @malcolmbrooks.
=> rose_arch: improve exception message on no source

lib/python/rose/apps/rose_bunch.py, t/rose-task-run/31-app-bunch.t, t/rose-task-run/31-app-bunch/app/bunch_env_pass/rose-app.conf, t/rose-task-run/31-app-bunch/suite.rc
This allows rose bunch to evaluate environment variables passed through to its settings and args sections - particularly useful for how some of our suites are written. Adds in tests for this behaviour too.
@matthewrmshin please review 1
@kaday please review 2
=> Rose bunch: evaluate environment varibles in settings and args

bin/rose-stem, doc/rose-command.html, doc/rose-rug-stem.html, lib/python/rose/stem.py, t/rose-stem/00-run-basic.t, t/rose-stem/00-run-basic/suite.rc
Currently rose-stem requires the source trees to be valid FCM locations, however this is mostly for determining the project name. This change allows the user to manually specify this and so negate the need for the source trees to be under FCM. Some functionality (namely the mirror URL) won't work, but otherwise this seems fine.
I've added documentation, and some tests to make sure this works, and I'm testing it with the UM suite at the moment.
=> Allow manual overriding of project in rose-stem

etc/rose.conf.example, lib/python/rose/apps/rose_prune.py, lib/python/rose/suite_engine_procs/cylc.py, t/rose-task-run/34-app-prune-hosts-sharing-fs.t, t/rose-task-run/34-app-prune-hosts-sharing-fs/app/pruner/rose-app.conf, t/rose-task-run/34-app-prune-hosts-sharing-fs/suite.rc
To allow job hosts who share a file system to share the load for doing
an `rm -fr` command.
Use `task_jobs`, if available, to get list of job hosts. This is more efficient than using the `task_events` table.
=> rose_prune: shuffle job hosts

lib/python/rose/apps/rose_prune.py, lib/python/rose/suite_engine_procs/cylc.py, t/rose-task-run/35-app-prune-log-on-hosts-sharing-fs.t, t/rose-task-run/35-app-prune-log-on-hosts-sharing-fs/app/pruner/rose-app.conf, t/rose-task-run/35-app-prune-log-on-hosts-sharing-fs/suite.rc
A shuffle should allow the load for doing `rm -rf` to be shared between
job hosts who share a file system.
Close #1796.
=> rose_prune: remote logs: shuffle hosts

lib/python/rose/apps/rose_ana.py
Due to some intermittent failures with the KGO database in rose_ana we should probably add some extra protection around the SQL operations (the errors are platform/file-system related rather than problems with the code - but it's not going to hurt having a little extra checking)
=> Add extra logic to retry rose_ana KGO database operations after failures

lib/python/rosie/svn_pre_commit.py, t/rosa-svn-pre-commit/01-rosie-create.t
A suite trunk replaces gives you something like this in an `svnlook changed`:
```
D   s/u/1/7/3/trunk/
A   s/u/1/7/3/trunk/
U   s/u/1/7/3/trunk/rose-suite.info
```
The delete check was ignored, because it thought the changeset was to add a new suite.
@benfitzpatrick @arjclark please review.
=> rosa svn-pre-commit: should now stop trunk replace

lib/python/rosie/vc.py, t/rosie-create/02-copy-inter.t
On suite copy, if a destination prefix is specified, don't use source
prefix for the purpose of setting the `owner` string.
Close #1810.
=> rosie copy 2: use destination prefix

lib/python/rose/macro.py, t/rose-app-upgrade/10-prettify-trigger-bug.t
`trigger` state-fixing is run immediately after an app configuration is upgraded within `rose app-upgrade`. After the app is upgraded, the configuration object is dumped and prettified
to e.g. compress namelist syntax (e.g. `0,0,0,0,0,0` -> `6*0`).
This prettification is done in-place in current master, so the configuration object itself is
returned with these modifications. In the `trigger` state-fixing, this object is used and it can
lead to incorrect triggering based on these values. Further runs with `rose macro` or `rose edit`
will correctly fix these problems. 
This bug does not affect `rose edit`, which uses a different dump mechanism (and does it at different times).
The new test fails current master, passes on this branch.
=> rose app-upgrade: fix trigger conflict with namelist prettification

demo/rose-config-edit/demo_meta/app/06-complex-rule/meta/rose-meta.conf, demo/rose-config-edit/demo_meta/app/15-sort-key/meta/rose-meta.conf, demo/rose-config-edit/demo_meta/app/15-sort-key/rose-app.conf
This fixes metadata-check errors in the `demo/rose-config-edit/demo_meta` suite.
These pop up if you load the suite in `rose edit` and load all apps.
=> rose demo metadata suite: fix metadata errors

lib/python/rose/config_editor/data.py, lib/python/rose/config_editor/data_helper.py, lib/python/rose/config_editor/nav_panel.py, lib/python/rose/config_editor/panelwidget/summary_data.py, lib/python/rose/config_editor/updater.py
This speeds up `rose edit`, particularly for adding and deleting sections.
When deleting or adding sections in one of the summary panel windows
(including the custom STASH widget) the speed up can be around 2x -
larger or smaller depending on the total number of sections in a configuration.
The change works by caching the slower function calls in the post-change updating,
and by avoiding expensive treeview re-drawing when there's no change.
=> rose edit: speed up adding/deleting sections

lib/python/rose/apps/rose_arch.py, t/rose-task-run/36-app-arch-interrupted.t, t/rose-task-run/36-app-arch-interrupted/app/archive/rose-app.conf, t/rose-task-run/36-app-arch-interrupted/suite.rc
If the previous attempt to archive was killed, a subsequent retry will
do nothing. This is due to the premature insertion of the target in the
rose_arch database.
If the target is inserted after the command_rc attribute is set to 1, an
kill of the previous attempt should act like a fail.
I've also moved the db insertion to after the
`if target.status in (target.ST_BAD, target.ST_NULL):` block - I think it
should retry bad or null jobs each time, and it doesn't look like it does that -
am I wrong?
@matthewrmshin @kaday please review.
=> rose_arch: fix incorrect behaviour on retry.

lib/html/template/rose-bush/view-mode.html, lib/html/template/rose-bush/view.html, lib/python/rose/bush.py
Also added feature to make url(s) clickable when in text mode.
closes #1684 
@benfitzpatrick Please review
=> rose bush: view: default to escaping output HTML

lib/html/template/rose-bush/job-entry.html
As long as host is set, that is, and regardless of whether submit method
and submit method ID are set or not.
(To test, run a suite with a task that uses the wrong host for a job submission method, causing a submission failure. On master, the relevant Rose Bush job entry will not display the value of the host. On this branch, the relevant Rose Bush entry will now display the value of the host.)
@benfitzpatrick please review. (1 enough?)
=> rose bush: job-entry: always display host

lib/python/rose/macros/trigger.py, t/rose-macro/10-trigger-check.t
The logic for triggering options in duplicate namelists is not right.
When an option is enabled in one duplicate section but ignored in another,
a child of the latter option can get the wrong parent status and can be marked as 'enabled'.
This can only happen in duplicate sections where there are at least 2 levels of triggering.
There are actually 2 errors fixed here:
* `has_ignored_parent` was set outside the code loop over duplicate ids, so changing it to `False` affected the remainder of the loop
* the duplicate id was used to check if anything triggered it in `trigger_family_lookup`, but actually
we need to use the non-duplicate (root) id (e.g. `namelist:foo=bar` rather than `namelist:foo(1)=bar`).
The current master fails the new test with:
```
[V] rose.macros.DefaultValidators: …
```
=> rose macro: fix nested triggers for duplicate section options

lib/python/rose/macro.py
When a macro imports another module from the same directory as itself, the import
will fail in `rose edit` but succeed in `rose macro`, due to a slightly different treatment of
the module names (via the variable `as_name` in the code).
When importing a macro, we should add its base directory to the PATH.
@r-sharp and @scwhitehouse, please track this issue.
=> rose edit: macros: allow importing other modules from same directory

lib/python/rose/bush.py, lib/python/rose/suite_control.py, lib/python/rose/suite_engine_proc.py, lib/python/rose/suite_engine_procs/cylc.py, lib/python/rose/suite_run.py, t/rose-suite-clean/01-running.t, t/rose-suite-clean/03-only-2.t, t/rose-suite-clean/04-only-3.t, t/rose-suite-clean/05-only-4.t, t/rose-suite-clean/06-only-5.t, t/rose-suite-clean/07-only-6.t, t/rose-suite-restart/01-running.t, t/rose-suite-run/00-run-basic.t, t/rose-suite-run/07-port-file.t, t/rose-suite-run/08-pgrep.t, t/rose-suite-run/20-pgrep-conflict.t, t/rose-suite-shutdown/00-run-basic.t
Make use of host information in port file to detect running suites.
Delete cylc port file or rose suite host file if the system is able to detect that no process associated with the suite is running on the recorded host. This allows suite-run, suite-clean, etc to proceed if a suite is terminated with a left-over port file.
Close #1829. Fix #1831.
=> rose suite-*: more cylc-6.8.0 port file related

doc/rose-rug-task-run.html
The example app config is using the original "limit=" setting rather than the "pool-size" setting. This corrects that oversight.
@matthewrmshin - please review - one liner so should only need the one person.
=> rose bunch documentation: Correct typo in example.

lib/python/rose/date.py, lib/python/rose/suite_engine_proc.py, t/rose-task-env/01-integer-cycling.t, t/rose-task-env/02-360day-cycling.t, t/rose-task-env/02-360day-cycling/app/foo/rose-app.conf, t/rose-task-env/02-360day-cycling/suite.rc
rose task-env was not working correctly with alternate calendars like
360day, etc. This change fixes #1842.
@benfitzpatrick @arjclark please review.
=> rose task-env: obey calendar mode

lib/python/rose/config_editor/updater.py
`rose edit` currently can get a target namespace (page/panel) ignored state incorrect
following triggering from another page. This is due to the change in #1758 which introduced
a cache for namespace ignored state. The cache needs to be cleared out when appropriate,
but isn't in this situation.
This change does a more thorough update of the target namespace (`update_namespace`
calls `update_ns_tree_states` as well) which clears the namespace ignored state cache and
will also do some more checking, which I think is appropriate. It doesn't appear to have a
noticeable effect on performance - I wouldn't expect it to.
An example `rose-app.conf`:
```ini
[env]
SWEET_STUFF=true
[namelist:food]
biscuits=2
doughnuts=1
steak=1
```
and metadata:
```ini
[env]
[env=SWEET_STUFF]
type=boolean …
```
=> rose edit: fix other namespace state display on trigger

doc/etc/rose-rug-advanced-tutorials-upgrade-dev/rose-meta.conf.html, doc/rose-rug-advanced-tutorials-upgrade-dev.html, doc/rose-rug-advanced-tutorials-upgrade-usage.html
This fixes #1069 and two other minor documentation flaws.
=> rose documentation: fix metadata for upgrade-dev tut

lib/python/rose/config_editor/__init__.py, lib/python/rose/config_editor/upgrade_controller.py
This fixes #1812.
What would really be helpful is if GTK indicated that a cell had a dropdown list with e.g. a small down arrow - as setup on our system, it doesn't, so I've added some text to tell the user what to do. It's not elegant, but it gets the job done.
To reproduce #1812, load e.g. a UM 10.4 app, which is already at the latest major version. Minor versions will be the ones belonging to upgrade macros immediately following UM 10.4.
@kaday, @matthewrmshin please review.
=> rose edit: upgrade: fix apply button sensitivity, instructions

t/rose-task-run/07-app-arch.t
New tests introduced by #1736 is broken by cylc/cylc#1727. (If suite is run in debug mode, cylc now switches on `set -x` for job files) This fixes the problem by filtering the output in `job.err`.
@benfitzpatrick please review. (I think 1 review is enough.)
=> t: fix breakage by cylc/cylc#1727

lib/python/rose/config_editor/updater.py
This fixes a problem where errors flagged by macros (including `fail-if`) were not displaying
in the left hand tree panel in `rose edit`. This is fairly longstanding - since Rose `2015.08.0`!
You can test it by e.g. deliberately violating a fail-if condition in an app. There will be an error for the variable on a page, but not on the left hand page panel. In this branch, it will work OK.
The change switches on the `refresh_ids` update of namespaces and `sub_data` which is the
duplicate-sections-summary-panel information - e.g.  the UM STASH widget. This now correctly
displays the errors.
To mitigate the effect of updating the sub data more often, which would cause a big slowdown,
I've consolidated it so that it only gets called once per `refresh_ids` call rather than once per
affected …
=> rose edit: fix left hand tree panel error icons for macros

lib/python/rosie/ws_client_auth.py
This fixes #1790.
When a password is not present in `gpg-agent`, and when `gpg-agent` prompting is off (our usual default), then report an error and then fall through gracefully to our manual prompting and allow `rosie` to continue.
Replicate by launching `gpg-agent` without entering any password on a server, then launching e.g. `rosie hello` with a remote prefix. The current master will silently break, and this branch will report a gpg-agent error on the terminal and then launch a prompt.
`rosie` and `gpg-agent` continue to work as they did before in the absence of `--batch` option to `gpg-agent` (i.e. when it is allowed to launch its own prompts).
@kaday, @matthewrmshin please review.
=> rosie go: better gpg-agent cache expiry handling

lib/python/rose/config_editor/__init__.py, lib/python/rose/config_editor/panelwidget/summary_data.py, lib/python/rose/gtk/util.py
closes #1710 
- Added functionality to delete / ignore sections using `Delete` and `Ctrl + I` respectively.
- Enabled multiple selection for BaseSummaryDataPanel
=> rose edit: keyboard shortcuts for multi section summary panel

t/rose-suite-restart/00-no-run.t
cylc/cylc#1774 introduces a small change to how `RegistrationError` is reported. (It no longer quotes the error string.)
@benfitzpatrick please review. (I believe 1 review is enough.) The test will only pass on latest cylc master.
=> t: fix string test broken by cylc/cylc#1774

doc/rose-configuration.html, doc/rose-rug-task-run.html, lib/python/rose/app_run.py, t/rose-app-run/23-file-both.t
Suppose we have both `file/whatever.txt` and `[file:whatever.txt]source=somewhere/whatever.txt`, the setting in the `rose-app.conf` should take precedence. A bug in the logic meant that this was not the case. This has now been fixed.
@benfitzpatrick @arjclark please review. This bug was reported via email by @hjoliver and @jonnyhtw.
=> rose app-run: fix file installation clash

lib/python/rose/apps/rose_bunch.py, t/rose-task-run/37-app-bunch-rm-old.t, t/rose-task-run/37-app-bunch-rm-old/app/buncher/rose-app.conf, t/rose-task-run/37-app-bunch-rm-old/suite.rc
Caters for a bug encountered in an odd situation.
If someone runs a bunch task in a suite and then later runs the suite and that same bunch task again (as a new first run), without having cleared out the work directory rose bunch will skip tasks it ran previously.
This fixes the bug. Test added here that should fail on master.
@benfitzpatrick - please review 1
@matthewrmshin - please review 2
=> rose bunch: remove any existing database entries if first submit

bin/rose-config-edit, doc/rose-command.html, lib/python/rose/config_editor/main.py
Closes #1273 
Namespaces passed as arguments to rose edit will now open on load. Passing partial namespaces is supported, e.g. the namespace `abc/def/foo/bar`, `foo` could be specified using any of: `abc/def/foo` `def/foo` `f/foo` `f/f` `foo` `f`. ~~In the case that multiple namespaces match the provided string the first match is used~~ The shortest namespace that matches will be opened i.e. `/env` before `/foo/bar/env`.
=> rose edit: added ability to specify initial namespaces.

lib/python/rose/suite_engine_proc.py, lib/python/rose/suite_engine_procs/cylc.py, lib/python/rose/suite_run.py
Don't call `cylc refresh` on reload mode, as it may nuke the passphrase
by calling un-register and register on the suite.
See also cylc/cylc#1774. Close #1846,
=> rose suite-run --reload: allow suite title change

lib/python/rose/suite_engine_procs/cylc.py, t/rose-bush/07-cycles-page.t
Cycles with only waiting tasks should not be displayed.
=> rose bush: cycles: don't display empty cycle

lib/python/rosie/browser/__init__.py, lib/python/rosie/browser/main.py
Closes #1874 
Adds a dialog to capture the SuiteNotRunning exception being thrown on trying to launch gcylc from withing rosie go for a non running suite.
@matthewrmshin - please review 1
@kaday - please review 2
=> Handle SuiteNotRunning error in rosie go.

lib/html/template/rose-bush/job-entry.html
There may be a delay before the batch system completes writing data to `job.err` and `job.out`. On job completion, they may appear to be zero-size, and get registered to the database as such. The files are then populated with data. This change ensures that these files get linked.
=> rose bush: job entry: link 0-size file any way

lib/python/rose/stem.py, t/rose-stem/00-run-basic.t
The `_MIRROR` variable in rose-stem isn't being set correctly when the command is invoked from within a subdirectory, it should have the base path of the URL, but it currently includes the path to the location where the command was run. This aims to fix it, and also to add a test which would have showed up the issue.
=> Rose stem mirror variable incorrect when run within subdirectory

lib/python/rose/stem.py, t/rose-stem/00-run-basic.t
The test on whether the project of the rose-stem source tree was determined correctly is a few lines too late - it comes after the project variable is actually used to determine a possible mirror, and if the project is not found the code aborts in mirror determination as it tries to do a regular expression on `None`, before the test would generate a nice error.
The fix is to move the test a couple of lines up, so it's checked immediately after it tries to work out the project.
=> Project not found error tested too late in rose-stem

CONTRIBUTING.md, doc/rose-configuration-metadata.html, doc/rose-rug-metadata.html, lib/python/rose/macro.py, t/rose-app-upgrade/11-upgrade-basic-tree.t, t/rose-app-upgrade/12-downgrade-basic-tree.t, t/rose-macro/23-import-tree.t
Close #1862 
* Allow for upgrade macros to work when the meta-data directory structure has a greater depth than 1 level
* Add platform agnostic python bulletins around the above code change.
=> app-upgrade: Allow multi depth metadata directories to work with upgrade macros

lib/python/rose/macros/trigger.py, t/rose-macro/10-trigger-check.t
The `trigger` mechanism in transform macro mode (`rose macro`, and `rose edit` for trigger error checking) can sometimes (rarely?) be incorrect.
The code currently does:
```python
for var_id in self.trigger_family_lookup:
self.update(var_id, config, meta_config)
```
where `self.update` launches a cascading check down the trigger chain from `var_id`.
These cascading chains will overlap, and every setting will be checked at least once, but the unordered nature of the `for` loop means that in some particular cases the ignored status of a parent will not get properly transmitted to an ignored status for a child.
The new code loops over ids based on their maximum rank in the trigger hierarchy, from lowest to highest. This means that any parent should propagate their status properly (reliably!) …
=> rose macro: fix trigger transform order-sensitivity bug

t/rose-suite-scan/00-localhost.t, t/rose-task-run/38-app-bunch-counts/app/cutoff/rose-app.conf, t/rose-task-run/38-app-bunch-counts/suite.rc
The rose-suite-scan/00 test is passing dubiously any way. After the port file
change in cylc, it is running `grep` on the wrong thing. The problem was picked
up under Ubuntu 16.04 due to it being more unstable.
Ubuntu runs dash instead of bash by default, so the double bracket syntax for
numeric comparison in the new rose_bunch test does not work. Modifying it to use
the old `test` command allows the test to work as intended.
=> t: allow tests to pass on Ubuntu 16.04LTS

doc/rose-rug-suites-I.html
Addresses a common misconception we have when delivering training courses r.e. cyclepoints vs. realtime and adds a link to the tutorial on that.
File has been run through tidy which has adjusted a few lines. Additional content is lines 510-513.
@matthewrmshin - please review. Should only need the one review.
=> suites-I slides: Add note on real-time clock triggering to suites-I slides.

doc/rose-rug-advanced-tutorials-clock-triggered.html
Adds a final cycle point offset of +P1D to the clock triggered tutorial.
Reasoning: we've seen people leave this suite running and forget about it on several occasions now, this just means it'll shutdown after a day's worth of cycling rather than running forever.
@matthewrmshin - please review. As original tutorial author I don't think this needs a second review but feel free to assign one if you see fit.
=> clock trigger tutorial: Add a final cycle point offset

lib/python/rose/macro.py, lib/python/rose/upgrade.py, t/rose-app-upgrade/00-null.t, t/rose-macro/00-null.t
Closes the suite-level aspect of #1498
@arjclark Please Review
=> rose macro: suite level functionality

bin/rose-date, doc/rose-command.html, lib/python/rose/date.py, t/rose-date/00-basic.t
Improvement on #1806 
At pressent the `--as-total=FORMAT` option only works when provided with a duration as in use case 3
- e.g: `rose date --as-total=S PT1H`
This change enables the option to be used when printing a duration as in use case 2
- e.g.: `rose date date1 date2 --as-total=M`
=> rose date: enable --as-total option when printing durations

doc/rose-configuration.html, lib/python/rose/app_run.py
Addresses a small part of #129.
(I'm starting at the beginning - app-run isn't actually particularly bad).
pylint (correctly, I think) identified that the old `_poll` method was a bit too big, so I've split it up.
After the split up, I thought that it would be better in its own class. Very little code blocks are
actually changed.
I've also trimmed `_prep`.
Pylint score now at 9.61/10 (`cd lib/python; pylint rose/app_run.py`) from 9.46. I'm OK with the remaining warnings. To be honest, in the future, code over 9.25 (say) should probably just be ignored.
@oliver-sanders, please review 2.
=> rose.app_run: increase pylint score

lib/python/rose/upgrade.py, t/rose-app-upgrade/03-complex.t
Currently, calling the `change_setting_value` MacroUpgrade method with `forced=True` (add if missing) will cause the following traceback:
```
File "/opt/python/runpy.py", line 122, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/opt/python/runpy.py", line 34, in _run_code
exec code in run_globals
File "/opt/rose/lib/python/rose/upgrade.py", line 671, in <module>
main()
File "/opt/rose/lib/python/rose/upgrade.py", line 638, in main
combined_config_map, meta_config, macro_function, macro_name=macro_id)
File "/opt/rose/lib/python/rose/macro.py", line 1110, in apply_macro_to_config_map
return_value = macro_function(macro_config, meta_config)
File "/opt/rose/lib/python/rose/upgrade.py", line 630, in <lambda>
conf, meta, …
```
=> rose app-upgrade: fix change_setting_value with forced=True

lib/python/rose/config.py, t/rose-macro/20-opt-conf-change-modify.t
This fixes a bad bad bug in `rose macro` and `rose app-upgrade` when handling optional 
configurations with sections that have different comments or different state from their parent. The bug would completely remove the additional options within that section from the optional configuration.
For example, an app config that looks like this:
```ini
[env]
FOO=baz
[namelist:foo]
```
with an optional configuration that looks like this:
```ini
[env]
FOO=bar
[namelist:foo]
baz=5
```
and metadata that looks like this:
```ini
[env=QUX]
compulsory=true
```
when ran through `rose macro --fix -y` will end up with a rose-app.conf like this:
```ini
[env]
FOO=baz
QUX=
[namelist:foo]
```
and an optional configuration missing the additional option in `namelist:foo`:
```ini
[env]
FOO=bar
[namelist:foo]
``` …
=> rose macro, app-upgrade: fix section comment removal of options bug

lib/python/rose/config_editor/util.py
Closes #1680 by not displaying "old_value" in info box. Previous value can already be seen via the hover over for the variable.
@benfitzpatrick - please review 1
@oliver-sanders - please review 2
=> rose edit: Don't show "old_value" in info dialog.

lib/python/rose/macro.py, t/rose-macro/14-duplicate-check.t
This allows a greater range of characters in the indices for duplicate settings.
This is prompted by the move towards including profile names in the indices for UM STASH namelists - many of these have characters like `+`, etc.
@scwhitehouse - this is kind of necessary for the above UM change, since past and current Rose will not recognise a namelist like `[namelist:foo(t+5_abcdef01)]` as a member of `[namelist:foo]`, so the metadata including triggering information will be lost.
=> rose configuration: allow more characters in setting indices

lib/python/rose/config_editor/panelwidget/summary_data.py
This fixes a problem where selecting certain right click menu items in the summary panel (e.g. the UM STASH panel) causes a GTK segfault.
@matthewrmshin, @oliver-sanders please review 1 and 2.
=> rose edit: fix right click menu segfault in summary panel

doc/rose-install.html
Close #1922. I now think it is best to up cherrypy version than hacking a fix in. Supersede #1924.
=> rose web service now requires cherrypy 3.2.2

lib/python/rose/macro.py, lib/python/rose/upgrade.py, t/rose-macro/24-prompt.t, t/rose-macro/lib/custom_macro_prompt.py, t/rose-macro/test_header
Closes #1650, #1688.
- no longer prompts for `optional_config_name`
- now only prompts once for unknown values when using optional configs
@benfitzpatrick Please review
=> rose macro: removed un-necessary prompting with opt configs

lib/python/rose/config_editor/updater.py
This fixes a traceback when a variable triggers a section which is missing from the configuration (a latent section):
```
File "/opt/rose/lib/python/rose/config_editor/valuewidget/radiobuttons.py", line 86, in setter
self.set_value(self.value)
File "/opt/rose/lib/python/rose/config_editor/variable.py", line 141, in _valuewidget_set_value
self.var_ops.set_var_value(self.variable, value)
File "/opt/rose/lib/python/rose/config_editor/ops/variable.py", line 274, in set_var_value
self.trigger_update(variable.metadata['full_ns'])
File "/opt/rose/lib/python/rose/config_editor/updater.py", line 216, in update_namespace
skip_sub_data_update=skip_sub_data_update)
File "/opt/rose/lib/python/rose/config_editor/updater.py", line 238, in update_status …
```
=> rose edit: fix trigger latent section traceback

doc/rose-rug-task-run.html
@benfitzpatrick - instances references corrected. Should only need 1 review as is a typo correction.
=> Correct rose bunch doc "instances" entries to "command-instances"

lib/html/template/rose-bush/job-entry.html
A `.label-important` managed to slip the net in #1891.
@benfitzpatrick Please review.
=> rose bush: fixed depreciated bootstrap 2 class

t/rose-task-run/01-run-basic-iso.t, t/rose-task-run/01-run-basic-iso/suite.rc, t/rose-task-run/03-env-basic-iso/suite.rc
Ensure a future cycle offset generates a `ROSE_DATAC__????` environment variable.
@arjclark please review and/or reassign. Looks like we don't have a test for this documented functionality.
=> t: rose task-env: ROSE_DATAC__????

doc/rose-rug-advanced-tutorials-bunch.html
Typo corrected.
@benfitzpatrick - corrected. Only needs the one review.
=> rose bunch tutorial: Correct [bunch]name= to [bunch]names=

lib/python/rose/bush.py, lib/python/rose/suite_engine_procs/cylc.py
Instead of performing an expensive query to get last activity time for rose bush pages (jobs/cycles) we can use the os.stat function instead as we do on the suites summary page.
@benfitzpatrick - please review 1
@oliver-sanders - please review 2
=> rose bush: use os.stat to get last_activity_time in all rose bush pages.

t/rose-config-edit/00-pytest.t, t/rose-config-edit/test_header
Don't display traceback on failure to import pytest module, and bring test file in line with our normal style.
=> t: rose-config-edit-00: fix traceback display

t/rose-config-edit/00-pytest.t
Detect missing "mock" Python module in skip logic.
Supply `${TEST_SOURCE_DIR}` as argument to `py.test`.
Follow up of #1929 and #1941.
=> t: rose-config-edit-00: fix py.test argument

lib/python/rose/macros/rule.py, t/rose-macro/09-rule-check.t
This fixes referring to top-level-option ids in the `fail-if` and `warn-if` rules.
I can't find any fail-if/warn-if metadata that might alter behaviour as a result of this change (needs to accidentally match `=[\w-]` which is not likely).
@matthewrmshin, @oliver-sanders please review.
=> rose metadata: fail-if: fix top-level-options

lib/python/rose/macros/rule.py, t/rose-macro/09-rule-check.t
This fixes an unintended consequence of #1943 that has cropped up in some real metadata. `=0` was being parsed as a top-level-option!
@matthewrmshin please review.
=> rose macro: fail-if: fix parsing '=0' as an id

lib/python/rose/config_editor/main.py
This improves the error traceback given if something breaks in rose edit during loading. It now gives the original traceback with and without debug mode.
It can be tested by manually adding an e.g. `raise Exception('oh dear!')` line somewhere in the loading process.
@matthewrmshin please review.
=> rose edit: clearer exception handling on startup

ACKNOWLEDGEMENT.md, lib/html/static/css/rose-bush.css, lib/html/template/rose-bush/suite-base.html, lib/python/rose/suite_engine_procs/cylc.py
This adds a submenu to the "cylc files" menu listing all log file (newest at the top). If there are no older log files it displays as before.
To be merged before https://github.com/cylc/cylc/pull/1958.
@benfitzpatrick Please review
@arjclark Please review
=> rose bush: add rotated log files to the "cylc files" menu

t/rose-bush/00-basic.t
Fix test broken since cylc/cylc#1827. The `-p` option means that we are copying the symbolic link. The `-r` option is unnecessary. @arjclark please review.
=> Fix t: rose-bush/00, broken since cylc/cylc#1827

lib/python/rose/upgrade.py, t/rose-app-upgrade/03-complex.t, t/rose-app-upgrade/07-add-existing.t
This dramatically speeds up adding and renaming settings in upgrade macros.
I've added some extra tests and it now gives out a warning when there is a duplicate
name clash (e.g. you want to rename something to `namelist:foo` but
`namelist:foo(1)` already exists).
@arjclark, @oliver-sanders please review.
=> rose app-upgrade: speed up adding or renaming for large configurations

lib/python/rose/config_editor/valuewidget/source.py
This fixes a traceback in rose edit where opening a `file` page results in:
```
File "/opt/rose/lib/python/rose/config_editor/nav_panel.py", line 491, in handle_activation
self._launch_ns_func(self.get_name(path), as_new=False)
File "/opt/rose/lib/python/rose/config_editor/main.py", line 733, in handle_launch_request
page = self.make_page(namespace_name)
File "/opt/rose/lib/python/rose/config_editor/main.py", line 867, in make_page
launch_macro_func=self.main_handle.handle_run_custom_macro
File "/opt/rose/lib/python/rose/config_editor/page.py", line 101, in __init__
self.generate_main_container()
File "/opt/rose/lib/python/rose/config_editor/page.py", line 674, in generate_main_container
self.show_modes)
File …
```
=> rose edit: fix source file page widget traceback

doc/rose-rug-config-edit.html, lib/python/rose/config_editor/__init__.py, lib/python/rosie/browser/__init__.py
This handles errors for site or user configuration for `rosie go` and `rose edit`.
If a user had e.g.:
```
[rose-config-edit]
should-show-custom-description=false
```
then this would evaluate to the string `'false'` instead of a boolean. This kind of error can be hard to debug. This change raises an exception if the (cast) type for an override option differs from the default
value's type, unless the default value is `None`.
I've also consolidated the override functionality since it was basically the same for `rosie go` and `rose edit`.
@arjclark, @oliver-sanders please review.
=> rose edit, rosie go: handle site/user incorrect value types

lib/python/rosie/suite_id.py
This handles a local suite Subversion problem where the working copy's files and directories are all missing and the `.svn/wc.db` file is itself corrupt (missing all of 'NODES' table entries). The svn status gives:
```
!       .
```
and `rosie ls` or `rosie go` crashes with:
```
File "/opt/python/runpy.py", line 122, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/opt/python/runpy.py", line 34, in _run_code
exec code in run_globals
File "/opt/rose/lib/python/rosie/ws_client_cli.py", line 279, in <module>
main()
File "/opt/rose/lib/python/rosie/ws_client_cli.py", line 270, in main
sys.exit(func(argv[1:]))
File "/opt/rose/lib/python/rosie/ws_client_cli.py", line 124, in list_local_suites
_display_maps(opts, ws_client, ws_client.query_local_copies(opts.user))
File …
```
=> rosie ls, go: handle corrupt working copy edge case

lib/python/rose/config.py, lib/python/rose/variable.py
These changes reduce the memory footprint of rose.config.ConfigNode objects and
rose.variable.Variable objects. It saves around 20% for `rose edit` memory use for a UM app I've tested, although I think we have further to go...
@arjclark, @matthewrmshin please review.
=> rose config, rose edit: reduce memory use

lib/html/template/rose-bush/job-entry.html
Use the greyed-out style for zero size file links.
There are two other situations where a file currently has the greyed-out text-muted style:
1) files whose transfer is in progress - but they already have a question mark to distinguish them
2) deleted files - these now have a strikethough to distingush empty from deleted.
=> Rose Bush: use muted text style for zero size file links

lib/python/rose/config_editor/util.py, lib/python/rose/variable.py
=> rose edit: fix info dialog for variables

bin/rose-stem, doc/rose-command.html
The command line help for rose-stem is missing the HOST_ variables introduced in issue #1898 .
=> Update command line help for rose-stem

t/rose-app-run/14-file-source-optional.t
A `namelist:` source is always considered out of date, so target is
always rebuilt, and so the modification time (via `ls -l`) of the target is not
something we should compare. The test should be stable if we only compare the files' SHA1 sums.
=> t: app-run 14: improve stability

lib/html/template/rose-bush/job-entry.html, lib/python/rose/bush.py, lib/python/rose/suite_engine_procs/cylc.py, t/rose-bush/02-no-job-out.t
Instead of using the suite runtime database table, use file system
listing and/or the listing of the members in relevant
`log/job-CYCLE.tar.gz` files.
* The change does not appear to have much performance impact for the job lists.
* It appears to be much faster when viewing a job log file.
* The only behaviour change is that jobs with their logs removed will no longer have their log files listed.
In view mode, fix no job entry display when file is TAR-GZ archived.
@arjclark @oliver-sanders please review.
=> rose bush: use file system for job logs listing

doc/rose-rug-suites-II.html
Makes the following changes to suites II tutorial:
* re-order some bullet points
* remove incorrect statement about spawn on demand
* fix broken image links
=> Suites II doc tweaks and fixes.

lib/python/rose/suite_engine_procs/cylc.py, t/rose-bush/00-basic.t, t/rose-bush/07-cycles-page.t, t/rose-bush/12-cycle-counts.t
Currently, if a cycle has waiting task proxies but no tasks in it that have run then it doesn't get displayed on the cycles page of rose bush. However, it does get counted at the bottom of the page "Entries X of Y" part. This can result in rose bush pages where the cycle counts are dramatically different from those being displayed.
This tweaks the query used to generate that count.
@matthewrmshin - please review (fixes the rose bush part of the problem seen in the VER suite the other day)
=> rose bush: only count cycles with things in for cycle counts.

lib/python/rose/suite_engine_procs/cylc.py, t/rose-suite-restart/02-basic.t, t/rose-suite-restart/03-host.t
cylc/cylc#1953 breaks `rose task-env` (and its derivatives). cylc/cylc#1958 breaks 2 similar tests. This change should fix both issues.
@arjclark please review or reassign.
=> Fix breakage by cylc/cylc#1953 and cylc/cylc#1958

lib/python/rosie/svn_post_commit.py, t/rosa-svn-post-commit/03-unicode.t
This fixes the attempt to decode value (always None) of an ignored
setting.
Fix #1981. @arjclark @oliver-sanders please review.
=> rosa svn-post-commit: fix ignored settings decode

t/rose-bush/00-basic.t, t/rose-suite-log/06-archive-star.t
Don't leave behind debug `foo` files.
@oliver-sanders please review.
=> t: remove debug foo files

lib/python/rose/config_editor/plugin/um/widget/stash.py
This fixes an inflexibility in the third-party `rose edit` UM STASH widget when importing packages from metadata (a demo piece of functionality). It also fixes a problem with duplicated attempts at adding sections.
=> rose edit: fix undesirable namelist name hardcoding

lib/python/rose/apps/rose_bunch.py
Corrects a typo.
@matthewrmshin - please review. Only needs one reviewer.
=> rose bunch: Correct typo in rose bunch error message.

doc/rose-rug-advanced-tutorials-retries.html
Updates the retry delays advanced tutorial to use `[[[job]]] -> execution retry delays`
=> Update retry delays tutorial to new cylc 6.11.x [[[job]]] syntax

bin/rose-bush, bin/rosie-disco, doc/rose-command.html, lib/python/rose/opt_parse.py, lib/python/rose/ws.py, t/lib/bash/test_header
With the new `--service-root` option, the URL of the ad hoc web service
will become e.g. `http://localhost:8080/rose-bush/`. This allows the
ad hoc server to be more similar to their WSGI counterparts.
=> rose.ws: ad hoc server: allow service name in URL

lib/python/rose/suite_engine_procs/cylc.py
rose_prune attempts to connect to the cylc suite run time database to
get a list of job hosts. If rose_prune was being invoked on non-suite
host, it would return a rather cryptic fail message. This change should
fix the issue.
=> rose_prune: fix bad fail message on non-suite host

bin/rose-macro, doc/rose-command.html, lib/python/rose/macro.py, lib/python/rose/opt_parse.py, t/rose-macro/00-null.t
Closes #1953 
Added `--suite-only` option to rose macro for running suite level macros only.
@arjclark Please review
=> rose macro: added suite-only option

lib/python/rose/macro.py, t/rose-macro/00-null.t, t/rose-macro/25-suite-level.t
Closes #1923 
If a transform and a validate method were defined in the same class then the transform macro would be run by `rose macro -V`.
@arjclark Please review
=> rose macro: don't run transform macros in validate mode.

lib/python/rose/config_editor/valuewidget/intspin.py
Closes #1540 
Switched from using gtk.SpinButton `value-changed` signal to the more generic gtk.Editable `changed` signal.
@matthewrmshin Please review / assign as needed
=> rose edit: fixed integer widget updating.

lib/python/rose/config_editor/valuewidget/array/entry.py
Closes #1851 
The EntryArrayValueWidget didn't update when a blank array element was removed. Removing the check doesn't seem to introduce any problems?
@matthewrmshin @arjclark Please Review
=> rose edit: allow removal of empty elements in compulsory arrays

lib/python/rose/config_editor/__init__.py
Closes #1648 
Sets the view default to show fixed variables. Haven't removed the functionality completely as it can still be useful to hide them.
@matthewrmshin, @oliver-sanders - please review
=> Change rose edit default to show fixed variables.

lib/python/rose/macro.py, t/rose-macro/24-optional-config-name.t, t/rose-macro/lib/custom_macro_prompt.py
Fix for functionality introduced in #1915 (and broken since).
- Fixes problem where the `optional_config_name` variable was always `None`.
- Added test.
@arjclark @matthewrmshin Please Review.
=> rose macro: fix macro optional_config_name kwarg.

lib/python/rose/config_editor/valuewidget/__init__.py
Closes #1512 
Changes the behaviour of environment variables when used with values metadata e.g:
```
[env=SOMETHING]
values=bar, baz, $SUITE_SOMETHING
```
Old behaviour:
- If an environment variable value is selected then display a textbox (only works if the value is selected before the panel is rendered)
- Else show a radio/combobox
New behaviour:
- Always display such settings as a radio/combobox (do not try to change to a textbox)
@arjclark @matthewrmshin Please Review.
@matthewrmshin On next release for the moment, bump milestone accordingly.
=> rose edit: better behaviour for enviroment variables in values metadata.

doc/etc/rose-rug-advanced-tutorials-macro/planet.py.report.html, doc/rose-api.html, doc/rose-rug-advanced-tutorials-macro.html, lib/python/rose/macro.py, t/rose-macro/00-null.t
Closes #1687 
Adds a new type of macro for reporting on application configurations, the main purpose of this is so that these macros don't get run by `rose macro -V`.
@matthewrmshin @arjclark Please Review
=> rose macro: add reporter macros

doc/rose-variables.html, lib/python/rose/apps/rose_bunch.py, t/rose-task-run/31-app-bunch.t, t/rose-task-run/31-app-bunch/app/bunch_print_envar/rose-app.conf, t/rose-task-run/31-app-bunch/suite.rc
Provides a `ROSE_BUNCH_LOG_PREFIX` environment variable to rose bunch instances.
Addresses #1919 part of #1954 
@matthewrmshin please review 1 - up to you if you want a review 2.
=> Provide ROSE_BUNCH_LOG_PREFIX to bunch instances.

lib/python/rose/config_editor/valuewidget/__init__.py
Closes #2012 
Addresses #1512 
Fixes logic introduced in #2010.
The new behaviour for environment variables in rose edit:
- Always display a text field if there is an environment variable in the value UNLESS an option widget (radio/combo) should be displayed AND the environment variable is listed as an allowed value.
@arjclark Please review / assign if necessary.
=> Fixed environment variable behaviour.

lib/python/rosie/browser/main.py
Use `pwd.getpwuid(os.getuid()).pw_name` instead of `os.getlogin()`. The latter can raise mysterious `OSError` in some environments. (Note: all other instances in our code use the former to get the current user ID.)
Reported by @dpmatthews.
@arjclark @oliver-sanders please review.
=> rosie go: use getpwuid to get current user ID

t/rose-suite-run/08-pgrep/suite.rc
Fix test failure due to old syntax being removed by cylc/cylc#2063.
@arjclark @oliver-sanders could one of you please review?
=> t: rose-suite-run-08: fix duration syntax

lib/html/template/rose-bush/pager.html
Pager template should no longer lose task/job status filters.
Reported by @scwhitehouse. @arjclark @oliver-sanders please review.
=> rose bush pager: fix lost task/job status filters

doc/rose-rug-suites-I.html
This replaces the Jinja2 looping part of suites-I with parametrization - the now preferred way of doing that.
Jinja2 is kept in but with a more relevant `if` block example.
A more more in-depth parameterization tutorial can be done in a follow up pull request if we feel this example and those given in the cylc user guide are insufficient (the cylc ones are pretty good tbh for any advanced usage of pure parameterization - I'm tempted to do a blended Jinja2 and parameters one though).
@matthewrmshin - please review 1 and make sure you're happy with the new baseline advice
@oliver-sanders - please review 2 (but wait till Matt's happy with the general gist first)
=> docs: Update suites-I to parameterization.

lib/python/rose/config_editor/main.py
Closes #1304 
Issue is also replicate-able using <ctrl + z>.
Issue is caused by multiple calls of the `perform_undo` function existing simultaneously.
=> Fixed concurrent undo issue.

lib/html/template/rose-bush/suites.html, lib/python/rose/bush.py, t/rose-bush/08-suites-page.t
Fix link to suites with slashes - the normal cherrypy magic
does not work here - suite names need to be proper arguments.
Ensure `os.walk` follows symbolic links when looking for suites.
=> rose bush: suites list: misc fixes

lib/html/template/rose-bush/job-entry.html
From user request. Browsers can attempt to auto-fill the sequential log forms.
Simple example to replicate:
- goto task-jobs page (for a suite with a task that has sequential logs)
- use the combo-box to view a log file
- press back in the browser
- try to open the log file again in the same way
=> bush: turned auto-complete off for seq-log forms.

lib/python/rose/config_editor/valuewidget/radiobuttons.py
Close #1936 
Turned out to be a really simple fix, see issue for reproduction instructions.
=> edit: prevent radio buttons from filling full page width

lib/python/rose/suite_clean.py, t/rose-suite-clean/01-running.t, t/rose-suite-clean/02-only-1.t, t/rose-suite-clean/03-only-2.t, t/rose-suite-clean/04-only-3.t, t/rose-suite-clean/05-only-4.t, t/rose-suite-clean/06-only-5.t, t/rose-suite-clean/07-only-6.t, t/rose-suite-clean/09-rmdir-2.t, t/rose-suite-clean/09-rmdir-2/app/t-1/rose-app.conf, t/rose-suite-clean/09-rmdir-2/rose-suite.conf, t/rose-suite-clean/09-rmdir-2/suite.rc
For suite under sub-directory hierarchy, clean all the way to the root
where possible.
=> rose suite-clean: improve parent directory clean

doc/rose-rug-suites-I.html
Mistakenly left an `endfor` in rather than an `endif` in for the refactored jinja2 part of the taught training slides.
=> Correct mistake in Jinja2 part of training slides.

lib/python/rose/suite_engine_procs/cylc.py
The new option replaces the old `--pyro-timeout` option. Bug detected while testing #2044.
=> rose suite-scan: fix `--comms-timeout` option

lib/python/rose/apps/rose_ana.py, t/rose-ana/00-run-basic.t, t/rose-ana/00-run-basic/app/db_check/bin/print_db_contents.py
Two slight problems have been identified with this functionality (though the impact is limited, only to those making use of the KGO database).  Two different problems exist:
**1.** The `rose_ana` re-write moved to using a buffer for the statment (to avoid many repeated calls to locking and/or commits to the database.  Unfortunately this defeats the point of the `tasks` database table - the original idea was that this table would initially be set to `1` for each task, and updated to `0` when the task finished (allowing scripts interfacing with the database the means to understand when something unexpected had stopped the task completing)...  Due to the use of the buffer everything is done in one go, meaning an unexpected error results in _nothing_ being written instead.  The solution is to …
=> Fixes for some issues with rose_ana KGO database

lib/html/template/rose-bush/job-entry.html
Disable links to zero-size files in the drop down box for sequential
logs. Close #2040.
=> rose bush: job entry: disable seq zero size

lib/python/rose/macro.py, t/rose-macro/25-suite-level.t
Fix traceback which occurs when running rose macro on a suite with both a rose-suite.info file and optional (rose-suite-xxx.conf) configs.
=> macro: fix bug with opt and info configs files.

lib/python/rose/config_editor/ops/variable.py
=> edit: remove errors before removing variables.

doc/rose-configuration.html
It looks like we are unable to accept `USER@HOST` syntax due to the usage of `urlparse` to get the scheme of the source location. (It is easy to fix the logic, but may add speed penalty to file install if not careful - so fix the doc for now.)
=> Fix doc on file install rsync user ID advice

doc/rose-configuration.html
Sorry an extra `</dd>` is left behind in #2065. This causes a failure on my desktop, (but not Travis CI for some reason).
=> Fix doc with extra </dd>

bin/rose-mpi-launch, t/rose-mpi-launch/01-command-inner.t
@matthewrmshin I have tested this in my own space and with:
`rose test-battery t/rose-mpi-launch`
and also demonstrated that without the fix the modified test fails. I decided to use file size (`ulimit -f`) rather than stack size as that is the default value that `-H` or `-S` reports. In practice `-a` is the option we would normally use, but that produces many lines of output and would have been harder to create a control.
=> Rose mpi launch

doc/rose-api.html
(The original link is currently broken, and also because we are already linking to Wikipedia a few lines above.)
=> Fix doc link: use Wikipedia for RDBMS definition

etc/rose.conf.example, lib/python/rose/suite_run.py, t/rose-suite-run/12-run-dir-root.t, t/rose-suite-run/19-restart-init-dir-remote.t
Support running `rose suite-run --remote=...` without invoking the login shell.
=> rose suite-run: no-remote-login-shell

lib/python/rose/apps/ana_builtin/grepper.py
Currently any of the file arguments being missing will result in the task raising an exception which (although this is caught correctly) means no entry is written to the KGO database...
It has emerged that it would actually be quite useful for our KGO update script to be able to effectively "install" new KGO files in the case that they are missing, so a simple change to treat the task as simply "failed" if the KGO file is missing has been suggested...
=> Allow `rose_ana` grepper classes to treat missing KGO files as failed tasks

doc/rose-rug-suite-control.html
Explain the usage difference between a suite configuration file and the
site/user configuration file.
=> doc: suite run root dir: clearer explanation

lib/python/rose/bush.py
Fixes issue where top level `cylc-run` dir was being treated as a suite directory and blocking user's other suites from dislaying in rose bush. Closes #2088.
=> Rose bush cylc-dir fix

doc/rose-configuration.html
The documentation for missing optional configuration keys (i.e. "(foo)" as opposed to "foo") appeared only to apply to the `opt-conf-key` command line argument and not to the environment variable `ROSE_APP_OPT_CONF_KEYS`.
=> Missing config key docs now generic.

lib/python/rose/macro.py
When `rose macro` prompts users to provide values the resulting input is passes through `ast.literal_eval`. If the user provides an unquoted value they see an "Invalid entry..." notice, that is, unless the value uses any python characters, in which case they will see traceback. File system paths are a good example of this, `filename` is fine whereas `../filename` causes traceback.
=> rose macro: improve feedback for invalid input

lib/python/rose/suite_run.py, t/rose-suite-run/24-host-log-timestamp.t, t/rose-suite-run/24-host-log-timestamp/suite.rc
Ensure that the TIMESTAMP of `log.TIMESTAMP/` match up between suite and
remote job hosts.
=> rose suite-run: matching remote log timestamp

.travis.yml
In response to cylc/cylc#2355, we need to have PyOpenSSL for the Python environment in Travis CI.
=> Add PyOpenSSL to Travis CI install

lib/python/rose/apps/ana_builtin/grepper.py
Since some programs report errors or useful additional information on `stdout` the `grepper` class should print both `stdout` and `stderr` when something has failed.
=> rose-ana grepper print stdout on failure

lib/python/rose/suite_restart.py, lib/python/rose/suite_run.py
Rank and threshold settings for suite host group were lost due to
premature value expansion.
=> suite-run/restart: fix host select logic

lib/python/rose/resource.py
`os.getenv` will return `None` rather than raising `KeyError` so the `try`/`except` was failing to catch the error.
=> Fix get_util_name exception.

lib/python/rose/macros/rule.py, t/rose-metadata-check/06-rule.t
Both `this(1)` and `len(this)` work but `len(this(1))` doesn't.
E.G:
```ini
[env=FOO]
length=:
warn-if=len(this(1)) > 2;
```
=> mini language: support len(this(N))

doc/rose-rug-suites-I.html
Remove a dead link that is causing the test battery to fail.
=> Doc: remove dead cylon image link

.travis.yml, doc/etc/rose-rug-advanced-tutorials-multi-inherit/race.html, doc/rose-install.html, lib/python/rose/bush.py, lib/python/rosie/ws.py, lib/python/rosie/ws_client.py, sbin/rosa-rpmbuild, t/lib/bash/test_header, t/rose-suite-restart/02-basic.t
They are the same module from Python 2.6+. This change removes this unnecessary external dependency.
=> Replace simplejson with json in standard library

lib/python/rose/config_editor/panelwidget/summary_data.py
The expanded selection was incorrectly updated in the event that the `TreeStore` was modified in a manner which caused a re-ordering of rows which in-turn affected a re-ordering of sections. This is a presentation layer bug as the underlying data-structure is not affected.
1. Open a widget which inherits from the `BaseSummaryDataPanel` class.
- Note: The data-structure will require at least 4 columns.
- Note: At least three sections must be present.
2. Group by one column.
3. Expand a section within it ensuring that:
- The section has 3 or more items.
- In the section, at least two columns where at least two values are present.
- The section is not the first in the panel.
4. Sort by **an even number** of columns (at least one of which must contain multiple values).
6. Change a value in …
=> Fix selection expanded after change.

lib/html/static/js/search.js, lib/html/template/rose-bush/view-search.html, lib/html/template/rose-bush/view.html
* When a line number is specified in the URL the line will be highlighted on page load.
* Selecting a line no longer requires a content reload.
* Highlighting of logger level information (i.e. `INFO`, `DEBUG`, ...) is now restored (broken by the new logging system).
@matthewrmshin please assign second review when the time comes.
=> bush: fix links to line numbers and syntax highlighting

lib/python/rose/bush.py, t/rose-bush/00-basic.t, t/rose-bush/14-doctest.t
Prevent paths from being passed in url parameters (note file access is moderated by `os.access`).
=> bush: prevent files being served outside of suite dir

lib/python/rose/config_editor/page.py
Steps to replicate:
1) Open `rose edit`.
2) Select `rose-suite.conf` from the tree menu.
3) Open the `page` menu.
=> Fix config edit traceback on page menu.

lib/python/rose/metadata_check.py, t/rosie.db/00-query.t
Allow check to pass for GTK widgets if there is no display in the environment.
Problem reported by @scwhitehouse.
=> metadata-check: ignore GTK widgets if no display

lib/python/rose/apps/rose_arch.py, t/rose-task-run/40-app-arch-duplicate.t, t/rose-task-run/40-app-arch-duplicate/app/archive/rose-app.conf, t/rose-task-run/40-app-arch-duplicate/suite.rc
It is possible to pass rose arch a pair of duplicate targets using the `[arch:(target)]` syntax e.g:
```
[arch:foo]
[arch:(foo)]
```
This PR catches the configuration error before it surfaces from sqlite to provide a more helpful error.
=> rose-arch: Raise error for duplicate targets.

lib/html/template/rose-bush/broadcast-events.html, lib/html/template/rose-bush/broadcast-states.html, lib/html/template/rose-bush/suite-base.html, lib/html/template/rose-bush/view-mode.html, lib/html/template/rose-bush/view.html
Use `?&suite=SUITE` instead of `/SUITE` in links.
Fix #2133.
=> rose bush: fix template: hierarchical suite names

lib/python/rose/macro.py, t/rose-macro/26-optional-config-name-2.t, t/rose-macro/lib/custom_macro_change_arg.py
Reported by @r-sharp. New test (which fails on current master) demonstrates the issue. The transform dies on an optional configuration that does not have the custom argument.
=> rose macro: fix transform opt with arg

CONTRIBUTING.md, lib/html/template/rose-bush/broadcast-events.html, lib/html/template/rose-bush/broadcast-states.html, lib/html/template/rose-bush/cycles.html, lib/html/template/rose-bush/suite-base.html, lib/html/template/rose-bush/suites.html, lib/html/template/rose-bush/taskjobs.html
Pages include:
* broadcast-events and broadcast-states
* cycles
* suites
* taskjobs
These pages are reasonably expected to update on a semi-frequent basis. For monitoring,
having them auto-refresh will ensure you will probably have the most likely data
at your fingertips if you have your browser open on rose-bush.
=> rose bush now auto refreshes some pages

lib/python/rose/metadata_check.py
In certain situations the `DISPLAY` variable can be provided where it is not appropriate.
=> Abort widget check if gtk 2.0 not available.

etc/rose.conf.example, lib/python/rose/apps/ana_builtin/grepper.py, lib/python/rose/apps/rose_ana.py, sphinx/api/built-in/rose_ana.rst, sphinx/ext/rose_domain.py, sphinx/tutorial/rose/furthertopics/rose-stem.rst, sphinx/tutorial/rose/furthertopics/rose-stem/tutorial.rst
**Built on #2170, merge after**
Migrate the rose stem user guide into the new rose documentation. Some documentation moved into the codebase, otherwise a direct translation.
=> Rose user guide rose stem

.travis.yml, bin/rose-make-docs, lib/python/rose/apps/ana_builtin/grepper.py, sphinx/Makefile, sphinx/developing/building.rst, sphinx/tutorial/rose/summary.rst
~**Built on #2170, review after it is merged**~
It is possible for ``rose make-docs strict`` to pass but ``rose make-docs html`` to fail as some things, e.g. graphviz are only done as required. To pick up these errors TravisCI now runs *all* builds in "strict" mode.
=> rose make-docs: add --strict option

lib/python/rosie/ws_client_auth.py
``require_version()`` raises a ValueError 'if module/version is already loaded, already required, or unavailable' which was missing as an exception for the gi imports block.
=> Fix libsecret password manager (#2171) version check

lib/python/rosie/db.py, lib/python/rosie/ws.py
When the ``.metomi`` 'rose.conf' file does not contain valid information for either or both of 'mot' or 'mi' under the ``[rosie-db]`` setting, attempts to start an ad-hoc rosie disco server via ``rosie disco start`` and then access the 'mi' or 'mot' discovery databases will result in a long & obscure traceback (as below), which could be much improved with a try/except statement.
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
response.body = self.handler()
File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
self.body = self.oldhandler(*args, **kwargs)
File …
```
=> rosie disco: Catch attempts to connect to non-existent DB

404.md, _config.yml, bin/rose-make-docs, etc/deploy-docs, index.html, lib/python/rose/resource.py, rose.html, sphinx/_static/js/versioning.js, sphinx/_templates/layout.html, sphinx/_templates/versions.html, sphinx/conf.py, t/syntax/01-eslint.t
Add functionality to `rose make-docs` to build versioned documentation.
Documentation is built incrementally so new versions can be added without having to rebuild old ones i.e:
```console
$ git checkout 2018.05.0
$ rose make-docs
$ tree doc -L 1
doc
|-- 2018.05.0
|-- doc -> 2018.05.0
|-- index.html
`-- versions.json
$ git checkout some-future-version
$ rose make-docs
$ tree doc -L 1
doc
|-- 2018.05.0
|-- checkout some-future-version
|-- doc -> checkout some-future-version
|-- index.html
`-- versions.json
```
As the documentation is built incrementally it is non-destructive in version control terms meaning we can do:
```console
$ git push upstream gh-pages  # no need to -f force
```
This would make auto-deployment of documentation much nicer.
Static HTML redirects are created by `rose …
=> Rose user guide: versioning

sphinx/getting-started.rst, sphinx/index.rst
Add missing "getting started", translated from the old documentation with a few small changes.
=> doc: getting started

lib/python/rose/gtk/__init__.py, lib/python/rose/metadata_check.py
Further to #2141, #2169 
It would appear that the measures put in place still do not cover all cases. Note that `import gtk` in `rose.metadata_check` is equivalent to `import rose.gtk`.
For reference the offending function in `gtk` is `set_interactive` which is called on import in `gtk`: https://developer.gnome.org/pygtk/stable/gtk-functions.html#function-gtk--set-interactive
=> more reliable check for display capability

lib/python/rose/suite_run.py
This relates to #2103, which causes a similar issue for us. 
To repeat, we set: `root-dir=login*.archer.ac.uk=$DATADIR`. But in the submission command `$DATADIR` is interpreted on the rose/cylc server machine, which has no knowledge of what `$DATADIR` should be on the HPC. And so the suite directory is not created in the correct place. This doesn't seem to be an issue with the shell (as in #2103), as I use bash on both machines. 
Adding quotes around the value of the `root-dir` settings fixes it for us.
=> Fix root-dir settings for remote machine.

sphinx/api/built-in/rose_arch.rst
Compression scheme detection is compromised if there is a full stop symbol in the filename. This makes sense as we support `.tar.gz`.
Remove broken example from the documentation.
=> docs: fix broken rose_arch example

sphinx/tutorial/rose/furthertopics/index.rst, sphinx/tutorial/rose/furthertopics/rose-stem-tutorial.rst, sphinx/tutorial/rose/furthertopics/rose-stem.rst
Does this make sense?
| old url                               | new url |
| ----------------------------          | ---------------------------- |
| furthertopics/rose-stem.html          | furthertopics/rose-stem.html |
|furthertopics/rose-stem/tutorial.html | furthertopics/rose-stem-tutorial.html |
=> docs: change confusing rose-stem documentation structure

bin/rose-make-docs, sphinx/_static/js/versioning.js
Apparently extglob behaviour with dot-files is not completely standard across bash versions. Solve by removing `.git` from the the `DOC_VERSIONS` pattern as it is not needed there anyway.
=> fix ., .. versions and ensure .html url endings

sphinx/ext/rose_domain.py
This PR allows rose objects to be referenced from other Sphinx projects (i.e. Cylc).
Invalid references to rose objects from other projects will result in warnings which will cause a build failure if run in strict mode (same behaviour as referencing rose objects locally).
Unfortunately this is rather hard to test without creating a dummy sphinx project to reference from. Once we start using this in the Cylc documentation (and vice versa) it will be tested (by virtue of being used and failing on error).
Minimal example sphinx project to demonstrate intersphinx referencing.
*conf.py*
```python
import os
import sys
sys.path.append(os.path.abspath('ext'))
extensions = [
'sphinx.ext.intersphinx',
'rose_domain'
]
intersphinx_mapping = {'myrosedoc': ('http:/<url path to>/rose/doc/html', None)} …
```
=> docs: permit documenting rose objects via intersphinx

CONTRIBUTING.md, bin/rose-app-run, etc/rose-meta/rose_bunch/HEAD/rose-meta.conf, lib/python/rose/app_run.py, lib/python/rose/apps/rose_bunch.py, sphinx/api/built-in/rose_bunch.rst, sphinx/api/environment-variables.rst, t/rose-task-run/41-app-bunch-default-command.t, t/rose-task-run/41-app-bunch-default-command/app/buncher_default/rose-app.conf, t/rose-task-run/41-app-bunch-default-command/app/buncher_import/rose-app.conf, t/rose-task-run/41-app-bunch-default-command/suite.rc
This PR makes rose_bunch compatible with the default command lookup logic.
**Motivation:**
The `[bunch]commad-format` template is sometimes awkward to use. Firstly, it is expanded for environment variables, which makes it inconvenient for writing pieces of shell code. One might need to define variables in more complex commands (e.g.,  `for VAR in ...`), but kludges like `${VAR%}` are necessary to prevent their premature expansion in the command body.
Secondly, it makes factoring out bunching functionality out of the apps harder. One may reasonably want to have, say, a single app for deterministic and ensemble runs with a single `[command]default` for both cases and enable bunching through an optional config or app import on top of the main app config.
**Implementation:**
This PR makes …
=> command-format-less rose_bunch

lib/python/rose/config_editor/valuewidget/array/entry.py, lib/python/rose/config_editor/valuewidget/array/python_list.py, lib/python/rose/config_editor/valuewidget/array/spaced_list.py
Hi,
~Small change to compare the `list` using `not`, instead of comparing against another empty list.~
And also removes the part of the code that was trying to store the value of `list.remove`, which happens in place (but in Java if I remember well, `ArrayList#remove()` would return the element...).
Waited for Travis-CI to build my branch (https://travis-ci.org/kinow/rose) before submitting the pull request.
Happy to squash commits, rebase, or even add more unit tests if necessary :tada: 
Cheers
Bruno
=> Minor fixes for list removal

bin/rose-check-software, bin/rose-make-docs
The system we use to generate slides in the documentation (hieroglyph) is currently generating traceback for the latest Sphinx.
See: https://github.com/nyergler/hieroglyph/issues/148
HTML and PDF builds are unaffected.
Hardcode the sphinx version to the last working combination (1.7.9) until this issue is resolved.
=> Fix documentation build error

lib/python/rose/apps/ana_builtin/grepper.py
We recently made an adjustment to the way we interpret the KGO database entries produced by `rose_ana` tasks.  As a result sometimes the compared files include sym-links, and unfortunately the code in the current analysis functions calls `os.path.realpath` on the files.  The causes the sym-links to be followed and causes problems for our updating processes.  On closer inspection there's no reason why this needs to be `realpath`, so we change it here to use `abspath` instead (which is essentially the same, save for the sym-link following part)
=> Fix for path functions in grepper

sphinx/tutorial/cylc/runtime/configuration-consolidation/jinja2.rst
Fix typo in a Jinja2 multi-line statement example. Trivial hence a single reviewer sufficient.
(I don't have time to trawl through docs to check for typos, but will try to report as & when I spot them.)
=> docs: fix typo breaking example code

sphinx/tutorial/cylc/furthertopics/suicide-triggers.rst
After a brief flirt with "or" logic (https://github.com/cylc/cylc/pull/2523, https://github.com/cylc/cylc/pull/2656) suicide triggers now combine with "and" logic so a suicide trigger example is no longer valid.
Fix the example and add a note explaining how suicide triggers work (as inverse logic seems to infer an inverse conditional).
@matthewrmshin please assign second.
=> docs sucide trigger change to and

t/docs/01-doctest.t
Command was not updated after it was renamed causing the doctests to always get skipped.
=> fix doctests

lib/python/rosie/browser/main.py, lib/python/rosie/ws_client_auth.py
Fix #2245 
This appears to fix the problem. I'm uncomfortable with the level of explanation I can provide for why it works. As far as I can tell a number of the later imports refuse to work if other libraries (`pygtk` in particular) have been loaded first.
=> rosie go: libsecret authentication caching issue

bin/rose-make-docs, etc/rose-docs-env.yaml
Add conda environment file for installing the Python dependencies for the rose documentation builder. This is more documentation than functional change.
* Keep it simple for now, create a proper environment for Rose later.
* It might be possible to install other dependencies but these would include graphviz, latex, etc which would be a little heavy handed.
* It would be possible to add an auto-installer similar to the `--venv` option but that doesn't really seem necessary.
@matthewrmshin I've put this on next release as it's non functional and should be pretty quick to review. Feel free to bump if not.
=> docs: add conda recipe

lib/python/rose/macro.py, sphinx/api/rose-macro.rst
Add documentation for a feature quietly slid in way back (#1915).
@r-sharp pinging you in on this one, do these docs make sense?
@matthewrmshin don't allow this to be a release blocker, bump to soon if we can't get it reviewed.
=> macro: document optional_config_name feature

etc/tutorial/consolidation-tutorial/.validate, etc/tutorial/rose-stem/.validate, etc/tutorial/rose-suite-tutorial/.validate, t/rose-bush/00-basic.t
Suppress debug level log entries in validate commands by not running command in verbose mode.
Modify tests to expect background `localhost` jobs to store host name entry as `hostname -f`.
See also: cylc/cylc#2781 and cylc/cylc#2849
=> Fix tests broken by cylc/cylc#2781 and cylc/cylc#2849

lib/python/rose/config_editor/valuewidget/intspin.py
Consider `meta/rose-meta.conf`:
```
[env=END]
type=integer
```
And `rose-suite.conf`:
```
[env]
END=201
```
Run `rose config-edit`, select *suite-conf -> env* and then backspace out the value of the `END` variable.
On master, `rose config-edit` crashes with a segmentation fault.
This branch fixes the issue.
=> gtk.SpinButton: fix seg fault on null value

.travis.yml, sphinx/developing/autodoc.rst
Looks like since the last successful build on `master`, Sphinx documentation has been updated.
One of its link, used in Rose's documentation, has changed. Causing the build to fail during the docs generation.
Also bumps up the distro to `xenial`, as Travis appears to be having issues with trusty to download artefacts from APT repositories - build#37 https://travis-ci.org/kinow/rose/jobs/461572030
After that, it is possible to see that APT packages are successfully installed, but on build#38 it failed due to the broken link (also failed in my PR for coverage #2230) https://travis-ci.org/kinow/rose/jobs/461573882
Once the `xenial` distro was in place, and the link was fixed to the latest I could find in their new website (hopefully got the right one), it passed successfully on my build#39 - …
=> Fix docs (sphinx link)

lib/python/rose/macro.py
After the `if` and `else`, I think there's no way for the extra `return` to be used.
=> Remove unreachable code in macro.py

lib/python/rosie/browser/suite.py
There's a call to `str(exc)` right below the `try/catch`. I think it was copy/paste'd, as `str(exc)` would fail in runtime?
Found doing a quick analysis of the project after working on the pull request for coverage, and before preparing things for Melbourne; so apologies for not doing thorough testing.
=> Name LocalCopyStatusError as exc, so that str(exc) works below

lib/python/rose/apps/ana_builtin/grepper.py
Looks like a fixed typo contains more characters than the typo - #2269. (Interestingly, my version of pycodestyle is not picking this up.)
=> Fix line length issue

.codecov.yml, .coveragerc, .gitignore, .travis.yml, .travis/cover.py, .travis/sitecustomize.py
Hi,
This is based on a [pull request submitted for Cylc](https://github.com/cylc/cylc/pull/2766), but with a few enhancements (which will be applied there too now).
The current [coverage reported in Codacy is **3%**](https://app.codacy.com/project/kinow/rose/dashboard), but it could be due to some bug in this pull request. Or maybe not all the code can be covered, and so it would be just a matter of ignoring more files... or maybe it is due to some configuration from Codacy that I forgot to change.
I finished this change yesterday, and have been playing with Codacy and Travis until now, trying to tweak the settings to see if there was anything obvious that I was missing. But perhaps somebody else would be interested in having a look at it? (if you compare my/rose Codacy dashboard, there …
=> Add coverage to project reports.

lib/python/rose/apps/ana_builtin/grepper.py
There's a bit of logic in the way the `grepper` class deals with the specification of the KGO files which leads to it spamming a message in an unhelpful way...
Currently the behaviour if the `kgo_file` input is completely omitted and the behaviour if it is provided but left completely empty are exactly the same.  As a result a `rose_ana` task which omits the setting because it doens't care about KGO at all (it may simply not use the concept of KGO) will print the message "No KGO files are present" for every single comparison made.  Clearly this is undesirable...
The solution is to reshuffle the logic so that the message is only printed in the case of the input being explicitly set to blank (with complete omission printing no messags at all)
=> Fix overzealous informational message about KGO in grepper class

bin/rose-check-software, etc/rose-docs-env.yaml, lib/python/rose/popen.py, sphinx/conf.py, sphinx/tutorial/cylc/img/iso8601-dates.svg, sphinx/tutorial/cylc/scheduling/datetime-cycling.rst
When I started out writing the Cylc tutorial I though LaTeX diagrams might be useful, however, it turns out that `graphviz` and `svg` cover most use cases better and there is only one LaTeX diagram in the documentation.
This PR converts the one LaTeX diagram to an SVG (editable via Inkscape) removing the LaTeX dependency (except for PDF builds) and adds superior SVG graphic support where appropriate tools / extensions are available.
=> remove docs latex dependency

lib/python/rose/suite_control.py
`rose suite-shutdown` currently fails with the current error:
```
NameError: global name 'host_name' is not defined
```
This seems to have slid through the test battery, we could add tests for it now but considering the imminent retirement of this command we may wish to leave as is for now.
=> rose suite-shutdown: fix traceback

lib/python/rose/suite_engine_procs/cylc.py
Following logging changes in Cylc, `rose suite-run` now spams users with `DEBUG` statements.
```console
$ rose suite-run
[INFO] export CYLC_VERSION=7.8.0
[INFO] export ROSE_ORIG_HOST=eld668
[INFO] export ROSE_SITE=
[INFO] export ROSE_VERSION=2018.11.0
[INFO] delete: log/rose-suite-run.conf
[INFO] symlink: rose-conf/20190122T140922-reload.conf <= log/rose-suite-run.conf
[INFO] delete: log/rose-suite-run.version
[INFO] symlink: rose-conf/20190122T140922-reload.version <= log/rose-suite-run.version
[INFO] 2019-01-22T14:09:23Z DEBUG - Loading site/user global config files
[INFO] 2019-01-22T14:09:23Z DEBUG - Reading file user/.cylc/global.rc
[INFO] 2019-01-22T14:09:23Z DEBUG - Reading file user/cylc-run/tmp.f0a2CJfOMd/suite.rc
[INFO] 2019-01-22T14:09:23Z DEBUG - Processing with Jinja2
[INFO] …
```
=> report debug statements only when requested

bin/rose-check-software, bin/rose-make-docs, etc/rose-docs-env.yaml, sphinx/conf.py, sphinx/ext/hieroglyph_patch.py
Temporary fix to allow the documentation to be built with contemporary versions of Sphinx (note v2.0 is under development).
=> docs: patch hieroglyph to work with sphinx 1.8.0+

sphinx/ext/cylc_lang.py
Support additional features of the Cylc suite.rc language to permit use in the Cylc documentation (cylc/cylc#2910).
Adds support for the following (see table in cylc/cylc#2752):
* Inter-Suite
* Include files
* xtriggers
* empy
Fixes:
* Line continuation characters in headings
```
[foo, \
bar]
```
* Cycle points in inter-cycle offsets
=> pygments syntax: improve cylc lexer

lib/python/rose/suite_engine_procs/cylc.py
Call `os.open(..., os.O_DIRECTORY)` on the suite's service directory
(i.e. the parent directory of the suite's contact file) before testing
for existence of the contact file. This ensures that the file system is
synchronised e.g. for NFS or the file existence test may fail even
though the file is already there.
=> Call opendir before testing contact file existence

sphinx/api/built-in/rose_prune.rst, sphinx/api/configuration/metadata.rst
I noticed a Sphinx formatting error under the ``rose-meta.conf[SETTING]values`` section in the online documentation & though I might as well put in a fix given it is straightforward. Whilst amending this I did a ``git grep "\:rose\:conf\`"`` to reveal one more instance of the same typo.
Trivial hence lone reviewer sufficient.
=> docs: add missing characters to fix formatting errors

lib/python/rose/config_editor/valuewidget/array/entry.py, lib/python/rose/config_editor/valuewidget/array/python_list.py, lib/python/rose/config_editor/valuewidget/array/spaced_list.py
Close #2272, which has been returned to as it has been noticed by another user in a different context (for the ``spaced_list`` type instead i.e. from within ``rose/config_editor/valuewidget/array/spaced_list.py``).
Upon investigation, the issue has arisen from the commit https://github.com/metomi/rose/commit/493750a2e4cdeac45ff664decb438ac82b1e13f7. The ``pop()`` method requires any argument to be an index instead of a matching element like ``remove()``. Admittedly this was a reviewing oversight on my part.
=> edit: fix bug w/ element removal on array-like types

lib/python/rose/macros/trigger.py
Besides searching for `== True` and `== False`, now I'm also searching for `== []` when syncing code :smile: 
I think these two statements are equivalent, but without creating an empty array (though I suspect compiler/interpreter/etc should optimize it)?
Cheers
Bruno
=> Simplify boolean expression

.travis.yml
The change of project name from cylc to cylc-flow has broken the automated rose tests. This is a quick fix.
=> fix location of cylc which is now cylc-flow

.travis.yml
Now that cylc/cylc-flow#2990 is merged, we should install cylc-flow in a different way for Travis CI.
=> Handle cylc-flow as a module

sphinx/api/configuration/metadata.rst
Several users have been confused about the behaviour of logical tests involving the membership operator ``in``. Specifically, ultimately many have assumed (e.g. ``trigger=env=``...) ``SETTING: this in 'VALUE'`` would evaluate  identically to ``SETTING: 'VALUE'``.
Looking at the documentation, I think we can make the Pythonic nature of ``in`` clearer by segregating it as a distinct test under an explicit "membership" title & providing some examples, as attempted here. Especially since many (most?) of our users are most familiar with FORTRAN, which doesn't seem to have an equivalent/similar operator, so it's behaviour might be non-intuitive to them.
Please let me know if I can make this clearer in any way. I wasn't sure if it was best to use an example with the smallest list allowing for …
=> metadata: clarify mini-language 'in' operator behaviour

sphinx/api/rosie-web.rst
Fix a couple of broken examples in the docs.
=> fix rosie REST API docs

.travis.yml, bin/rose-check-software, lib/python/rose/config_processors/fileinstall.py, lib/python/rose/job_runner.py, lib/python/rose/loc_handlers/fs.py, lib/python/rose/loc_handlers/namelist.py, lib/python/rose/loc_handlers/rsync.py, lib/python/rose/loc_handlers/svn.py, lib/python/rose/popen.py, t/rose-app-run/06-namelist.t
Early efforts to implement rose-fileinstall with asyncio.
I created a wee script
```bash
#!/bin/bash
sleep 10
svn "$@"
exit
```
and changed the reference in `loc_handlers/svn.py` to use this script rather than SVN proper. Using a test setup from `t/rose-app-run/11-file-incr-2.t` I ran:
`/usr/bin/time -v rose app-run --config=../config -q`
Which gave the following results:
| Measure | Master | This Branch |
| ---| ---:| ---: |
| User time (seconds) | 12.16 | 12.71 |
| System time (seconds) | 1.72 | 1.90 |
| Percent of CPU this job got | 15% | 58% |
| Elapsed (wall clock) time (h:mm:ss or m:ss) | 1:31.83 | 0:24.85 |
=> Rose fileinstall async (failing codecov)

etc/tutorial/consolidation-tutorial/suite.rc, etc/tutorial/cylc-forecasting-suite/suite.rc, etc/tutorial/rose-weather-forecasting-suite/suite.rc, etc/tutorial/runtime-tutorial/runtime, sphinx/tutorial/cylc/runtime/configuration-consolidation/families.rst, sphinx/tutorial/cylc/runtime/introduction.rst, sphinx/tutorial/rose/suites.rst
Rose 2.0 equivalent of https://github.com/metomi/rose/pull/2336
Since https://github.com/cylc/cylc-flow/pull/3168 went through (with surprisingly little fuss) we can now get rid of all the horrible `PYTHONPATH` mess we have been expecting students to put up with in the tutorial suite.
Will assign reviewers once tests pass.
=> tutorial suite: remove pythonpath

lib/python/rose/reporter.py
This requirement comes through `rose_ana` where non-unicode characters may appear in file differences. Currently this causes Rose to bail out with a `UnicodeDecodeError`.
This change allows the error to pass and dumps non-unicode to screen if decoding fails.
=> reporter: mojibake

lib/python/rose/config.py, lib/python/rose/config_tree.py, lib/python/rose/run.py, lib/python/rose/suite_run.py, t/rose-app-run/26-define-overrides.t
For {suite,app,task}-run commands one can override config setting on the command line with `--define [section]key=value` options. This doesn't work, however, for some special, top-level keys like `opts` or `import` because applying these overrides happens too late in the config loading process. This PR removes this limitation.
=> Refactor loading of define overrides

bin/rose-suite-run, lib/python/rose/config_processors/empy.py, lib/python/rose/config_processors/jinja2.py, t/rose-suite-run/26-jinja2-insert.t, t/rose-suite-run/27-empy-insert.t, t/rose-suite-run/28-rose-site-env.t
Implements https://github.com/cylc/cylc-flow/issues/2960#issuecomment-466043979 - a special  `ROSE_SUITE_VARIABLES` Jinja2 (EmPy) dictionary containing all variables inserted in template, so that their names can be resolved in a programmatic way.
=> Suite variable dictionary containing all variables inserted in template

sphinx/ext/rose_domain.py
Fix to counter an un-documented breaking change in Sphinx 2.1.0 resulting from the addition of a new attribute on the [`highlight` directive](https://www.sphinx-doc.org/en/2.0/usage/restructuredtext/directives.html#directive-highlight).
This doesn't affect 2019.01.x due to the removal of Python2 support in latest Sphinx.
=> docs: sphinx 2.1.0 compatability

sphinx/hyperlinks.rst, sphinx/tutorial/cylc/introduction.rst
Back-port of #2347, not too urgent but ideally we would slide this into next-release as it is a pretty straight-forward change.
=> 2019.01.x docs: fix what-is-cylc page

lib/python/rose/config.py
Turns out the test failure in #2330 *was* related.
This should fix the test battery.
=>  config.load: permit unicode filename

sphinx/tutorial/cylc/introduction.rst
The introduction page seems to be a bit broken, the slides are fine but the regular HTML version is lacking content.
This PR changes from manually defined slides (`autoslides=False`) to automatically defined ones as used throughout the rest of the documentation. The content remains unchanged.
=> docs: fix what-is-cylc page

sphinx/_static/css/metomi.css, sphinx/tutorial/cylc/scheduling/graphing.rst
* Reduce some of the wordiness
* Put `input` / `result` examples side-by-side
* Clean up slides
=> doc: simplify cylc graphing tutorial

etc/tutorial/consolidation-tutorial/suite.rc, etc/tutorial/cylc-forecasting-suite/suite.rc, etc/tutorial/rose-weather-forecasting-suite/suite.rc, etc/tutorial/runtime-tutorial/runtime, sphinx/tutorial/cylc/runtime/configuration-consolidation/families.rst, sphinx/tutorial/rose/suites.rst
Due to packaging changes Cylc no longer inserts itself PYTHONPATH meaning that PYTHONPATH could potentially be undefined.
This causes tutorial job scripts to break due to `set -u`.
Reported by @wxtim
**[edit]** on master remove `PYTHONPATH` altogether (in a follow-on PR) after https://github.com/cylc/cylc-flow/pull/3168
=> [7.x] cylc tutorial: don't depend on PYTHONPATH being defined

sphinx/tutorial/cylc/furthertopics/retries.rst
Currently under the 'Retries' section in the Cylc Tutorial Further Topics of the docs, it suggests *replacing* for:
```
[runtime]
...
[[roll_doubles]]
script = """
...
"""
```
the line containing``[[roll_doubles]]`` with:
```
[[roll_doubles]]
[[[job]]]
execution retry delays = 5*PT6S
```
But this means that the ``script`` setting is parsed under the ``[[[job]]]`` section, & invalidates the suite configuration. This ensures that the user adds the new section and setting below the defined ``script``.
=> docs: fix Cylc Further Topics: Retries example

sphinx/api/configuration/application.rst
=> doc: fix app poll delays syntax

sphinx/api/configuration/application.rst
Correct syntax is PT0S not 0. #2364 back port.
=> [2019.01.x] doc: fix app poll delays syntax

metomi/rose/apps/rose_ana.py, t/rose-ana/00-run-basic.t, t/rose-ana/00-run-basic/app/rose_ana_t5/file/kgo.txt, t/rose-ana/00-run-basic/app/rose_ana_t5/file/results.txt, t/rose-ana/00-run-basic/app/rose_ana_t5/rose-app.conf, t/rose-ana/00-run-basic/suite.rc
We have a few cases in our test suite of rose-ana taking a long time - typically when doing lots of file comparisons (in the worst case a rose-ana task with ~20 operations had 4 or 5 that took ~10 minutes each, for a total runtime of over an hour)
It seems like an easy win for all rose-ana users to make it able to run operations in parallel.  Given the way the analysis tasks are written (as classes/plugins) it seems it would lend itself most nicely to multi-threading rather than multi-process (despite the process approach generally being easier to manage)
=> Implement threading to speed up rose-ana (PR on Master)

.codacy.yml, .codecov.yml, .coveragerc, .travis.yml, .travis/now, ACKNOWLEDGEMENT.md, metomi/rose/app_run.py, metomi/rose/date.py, metomi/rose/suite_engine_proc.py, metomi/rosie/ws.py, pytest.ini, setup.py, tox.ini
The isodatetime module was recently renamed metomi.isodatetime ([PR 132](https://github.com/metomi/isodatetime/pull/132)). 
This PR changes the namespaces in cylc to reflect this.
=> Use metomi-isodatetime in preference to isodatetime

sbin/rosa-rpmbuild
Fix rpm creation for 2019.01.x branch.
Not needed on master since whole approach will need a re-think.
=> rosa-rpmbuild: doc js file no longer needed + fix duplicated file warning

setup.py
@oliver-sanders has release cylc-sphinx-extensions on PyPi because PyPi doesn't like having urls as sources in setup files.
=> modified setup.py to use release of cylc-sphinx-extensions

sphinx/tutorial/rose/furthertopics/optional-configurations.rst
The 'S' in toppings in tutorial (optional-configurations) was making the suite not run as intended. I have removed this rogue 'S'.
Tutorial now works as intended.
=> Very minor typo fix in tutorial

CONTRIBUTING.md, etc/tutorial/cylc-forecasting-suite/bin/get-observations, etc/tutorial/cylc-forecasting-suite/bin/get-rainfall
I had a couple of problems with the cylc & rose tutorials, specifically with the [cylc runtime configuration tutorial](https://metomi.github.io/rose/2019.01.2/html/tutorial/cylc/runtime/runtime-configuration.html#admonition-0) and the [rose suite configuration tutorial](https://metomi.github.io/rose/2019.01.2/html/tutorial/rose/suites.html#admonition-5).
This PR fixes:
- HTTP 403 error in the weather data API request
- KeyError that sometimes happens when no wind direction/speed data is served (thanks to Joe)
=> Fix tutorial

.gitignore
I have a `metomi_rose.egg-info` directory that is not ignored on this branch (but is on master)
=> Ignore *.egg-info dir

bin/rose-make-docs, etc/rose-docs-env.yaml
Hieroglyph Version 2.0.0 removes Python 2 compatibility. This changes pins the Python 2 Rose branch to Version 1.
=> pinned hieroglyph to version 1.x as V2 doesn't have python2 support

sphinx/tutorial/rose/suites.rst
I don't think it's clear that this suite won't run yet, and that we are only testing the installation and validation at this point.
=> tutorial-bug: Clarify that suite won't run _yet_

setup.py, t/rose-macro/00-null.t
I can't see why there is an upper limit to jinja2 - it was introduced when I created the package a year ago.
This test was broken on master.
=> Fix setup.py for use with Cylc8

lib/html/static/js/rosie-disco.js
In the query page of Rosie Suites Discovery, the "all revisions" checkbox wasn't working
=> Fix broken checkbox in rosie suites discovery

.gitignore, metomi/rosie/lib/html/static/js/rosie-disco.js
Cherry-picked #2418 - In the query page of Rosie Suites Discovery, the "all revisions" checkbox wasn't working
=> Fix broken checkbox in rosie suites discovery (master branch)

.gitignore, lib/python/rose/config.py, lib/python/rosie/db_create.py, lib/python/rosie/svn_hook.py, lib/python/rosie/svn_post_commit.py, lib/python/rosie/svn_pre_commit.py, t/rosa-svn-post-commit/03-unicode.t, t/rosa-svn-pre-commit/00-basic.t, t/rose-config/02-self.py
Fixes several bugs.
Pre-commit hook:
- Check validity of rose-suite.info in branches, not just trunk, for each transaction (this includes whether the file is present, whether the owner, title, project are specified)
- Ensure sections are not permitted in the info file
Post-commit hook:
- If the info file fail is not encoded in UTF-8, try latin-1 aka ISO 8859-1 for decoding (this decoding is necessary to store the info files values in the database)
- If owner, project or title missing in a historical commit, insert the string `'null'` into the database instead of no entry at all
`db_create.py`:
- Instead of returning if the post-commit hook fails, skip the revision and continue
=> Address pre-/post-commit hook issues

lib/python/rosie/svn_pre_commit.py, t/rosa-svn-pre-commit/00-basic.t
Split off the main hook-overhaul PR #2417. Gives more useful error messages
=> Pre-commit hook: Add messages to certain bad changes

metomi/rose/env.py
Allows usage like this:
```python
my_environ = {'foo': '42'}
env_var_process('$foo', my_environ)
```
=> env_var_process: add opt to provide environ dict

metomi/rose/config.py, metomi/rose/reporter.py, metomi/rose/tests/config.py, metomi/rosie/db_create.py, metomi/rosie/svn_hook.py, metomi/rosie/svn_post_commit.py, metomi/rosie/svn_pre_commit.py, t/rosa-db-create/00-basic-1.dump, t/rosa-db-create/00-basic-2.dump, t/rosa-db-create/00-basic-3.dump, t/rosa-svn-pre-commit/00-basic.t, t/rosa-svn-pre-commit/04-unicode.t
#2417 ported to master
> Fixes several bugs.
>
> Pre-commit hook:
> - Check validity of rose-suite.info in branches, not just trunk, for each transaction (this includes whether the file is present, whether the owner, title, project are specified)
> - Ensure sections are not permitted in the info file
>
> Post-commit hook:
> - If the info file fail is not encoded in UTF-8, <del>try latin-1 aka ISO 8859-1 for decoding</del> <ins>raise a useful error saying configuration files must be in UTF-8 (this applies to pre-commit hook too)</ins> (this decoding is necessary to store the info files values in the database)
> - If owner, project or title missing in a historical commit, insert the string `'null'` into the database instead of no entry at all
>
> `db_create.py`:
> - Instead of returning if …
=> Fix db-create, pre-/post-commit hooks

metomi/rose/loc_handlers/rsync.py, metomi/rose/loc_handlers/rsync_remote_check, metomi/rose/loc_handlers/rsync_remote_check.py, metomi/rose/popen.py, metomi/rose/tests/test_loc_handlers_rsync_remote_check.py
Fixes #2442 .
A script written in python2 and unconverted (bc it was a raw script) was being run with python 3. As a result it was returning a tuple when it shouldn't have been.
The script created by metomi/rose/2019.01.x:lib/python/rose/loc_handlers/rsync.py::lines 67-92 should be:
=> prevent rsync failure.

etc/rose.conf.example, metomi/rose/resource.py
Remove unused `rose-doc` configuration (used to be used to point at locally built docs, nowadays we just use the internet 😄)
=> conf: remove legacy rose-doc configuration

.github/workflows/test.yml, metomi/rose/app_run.py, metomi/rose/apps/rose_arch.py, metomi/rose/config_diff.py, metomi/rose/config_processor.py, metomi/rose/config_processors/fileinstall.py, metomi/rose/host_select.py, metomi/rose/macros/trigger.py, metomi/rose/meta_type.py, metomi/rose/reporter.py, metomi/rose/run.py, metomi/rose/suite_engine_proc.py, metomi/rose/suite_engine_procs/cylc.py, mypy.ini, setup.py
built on: https://github.com/metomi/rose/pull/2461
Done whilst validating the type hints added in #2461
Minimal changes required to allow mypy to pass, allowing future development of type checking.
=> mypy: configure rose to use mypy

.github/workflows/test.yml, CHANGES.md, bin/rose, setup.py
* Tornado 6+ does not support WSGI.
* Disable it for now, fix later.
* See https://github.com/metomi/rose/issues/2492
=> disco: temporarily disable disco

sphinx/hyperlinks.rst, sphinx/tutorial/rose/rosie.rst
This has started failing (presumably as a result of yesterday's change).
@dpmatthews can you check that the old hyperlink wasn't doing something super clever. Otherwise it's a 1 liner, assigning to @datamel  in the hope that we can fix this quick.
=> fixed SRS hyperlink

.github/workflows/test.yml, metomi/rose/scripts/rosa-rpmbuild
~Built on #2494 (cli change required for MacOS due to the way Python is installed)~
Closes #2447
=> actions: enable macos testing

metomi/rose/apps/ana_builtin/grepper.py, metomi/rose/apps/rose_arch.py, metomi/rose/apps/rose_prune.py, metomi/rose/check_software.py, metomi/rose/config_diff.py, metomi/rose/host_select.py, metomi/rose/loc_handlers/rsync.py, metomi/rose/popen.py, metomi/rose/suite_engine_procs/cylc.py, metomi/rosie/suite_id.py, metomi/rosie/svn_hook.py, metomi/rosie/vc.py, sphinx/api/command-reference.rst
Closes #2320 
Make the rose Popener run object always return stdout, stderr and retcode as str and not bytes. This allows removed of a number of checks elsewhere.
This is an oversight from my original conversion of Rose to Python 3.
=> Popen always decodes

sphinx/hyperlinks.rst
https://cylc.github.io/cylc-doc/latest/html/user-guide/index.html might also be a valid destination, especially since this is rose2.
What do you (reviewer) think?
=> fixed broken link.

metomi/rosie/suite_id.py, sphinx/api/command-reference.rst, t/rosie-id/00-basic.t
Closes #2432 
> Extract version control information from installed Cylc8 workflows for the rosie id command.
>
> Depends on: cylc/cylc-flow#3849
Requires #2509  merger to pass
=> Re-enable Rosie ID.

metomi/rosie/suite_id.py, metomi/rosie/tests/test_suite_id.py, pytest.ini
Companion to https://github.com/cylc/cylc-flow/pull/4548 (needs merging first for tests to pass here). Follow-up to #2510.
=> Update `rosie id` to use new JSON format for Cylc VCS logs

.github/workflows/test.yml, metomi/rose/rose.py, setup.cfg, setup.py
Closes #2523
* Convert setup file format to setup.cfg.
* Add pygraphviz opt dep.
* Add logic to metomi.rose.rose to provide more helpful error messages
when optional dependencies are not present.
* Add graphviz to CI deps.
=> setup: add pygraphviz opt dep

metomi/rose/date_cli.py
Closes #2524 
Easy test of whether this is working 
```
rose date
cd ~/rose/sphinx
make clean html
```
The second case should produce the warning on master, but not on this branch.
=> Rose Date only warns if run in an interactive shell

metomi/rose/apps/rose_prune.py, metomi/rose/suite_engine_proc.py, metomi/rose/suite_engine_procs/cylc.py, sphinx/api/built-in/rose_prune.rst
Follow up #2522 
Reflects a telephone conversation from earlier today:
=> renamed function job_logs_pull_remote → job_logs_housekeep_remote

metomi/rose/__init__.py, setup.cfg
* Move over to the `.dev` convention.
* I think this is safe now after the CLI changes, will find out when the tests fail...
* Make the setupools dep formal
* The setuptools dependency was missing (provides `pkg_resources`).
* This dependency is often omitted as it is vendored (i.e. used by pip), adding it for correctness.
* Pinning the setuptools version fairly arbitrary to the version used by cylc-flow.
=> bump version; make setuptools dep formal

metomi/rose/app_run.py, metomi/rose/etc/rose-meta/rose-app-conf/rose-meta.conf, metomi/rose/host_select.py, metomi/rose/popen.py, metomi/rose/run_source_vc.py, metomi/rose/suite_engine_procs/cylc.py, metomi/rose/tests/suite_engine_procs/test_cylc.py, setup.cfg, sphinx/api/configuration/application.rst, t/rose-app-run/08-poll.t, t/rose-host-select/00-basic.t, t/rose-host-select/01-timeout.t, t/rose-host-select/02-localhost.t
This closes #2552
Changes the command that gets run in the background, as follows:
```diff
ssh -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=8 <hostname> \
-    env CYLC_VERSION=<version> rose host-select-client
+    env CYLC_VERSION=<version> CYLC_ENV_NAME=<$CYLC_ENV_NAME> bash -l -c 'rose host-select-client'
```
=> Invoke host-select via bash login shell

CHANGES.md, metomi/rose/apps/fcm_make.py, metomi/rose/popen.py, metomi/rose/suite_engine_procs/cylc.py, metomi/rose/tests/suite_engine_procs/test_cylc.py, t/rose-task-run/08-app-fcm-make.t, t/rose-task-run/08-app-fcm-make/flow.cylc
closes: https://github.com/metomi/rose/issues/2553
Requires sibling cylc-rose to be checked out (https://github.com/cylc/cylc-rose/pull/120).
Credit to @wxtim for pairing this.
=> Fcm make fix for remote and subshell platforms

CHANGES.md, rose-version
Refer to https://www-nwp/~fcm/metomi-docs/team/how_to_create_a_git_release.html#before-you-start-first-time
=> 2019.01.6-pre-release

metomi/rose/scripts/rose-mpi-launch, t/rose-mpi-launch/03-commands.t
closes #2573 
Rose MPI launch fails if `ROSE_LAUNCHER` contains spaces.
=> Mpi launch fix

metomi/rose/date.py, setup.cfg
Use new names of Isodatetime interfaces.
=> update set_time_zone_to_... methods

metomi/rose/env_cat.py, metomi/rose/tests/test_env_cat.py
Fixes two bugs found by tester.
Handle this more elegantly.
Trying to write a string to a file handle opened in bytes mode.
The first commit is a refactor without functional changes to allow for testing, and tests for the issues described. Checking f8126199 out should cause two of the three tests (`pytest metomi/rose/tests/test_env_cat.py   -vv`) to fail.
The second commit 1abaca8fe3ae7ef655baf1cffab30a60a532704b fixes both problems.
By inserting print statements into the code I was able to ascertain that there coverage is now ~100%, though this is only a measure of quantity, not quality.
Tagged @oliver-sanders as a single Python test :. this is a smallish change with @dpmatthews as a functional tester.
=> Rose env cat fix

lib/python/rose/suite_run.py
Some deployments of Rose 2019 use Python 2 where the following snippet doesn't work:
```python
>>> "{}".format('foo')  
File "<stdin>", line 1, in <module>
ValueError: zero length field name in format
>>> "{_}".format('foo')
```
This led to a problem with the Cylc 8 checking method.
```bash
> ssh machine-with-python3.6-rose
> rose suite-run
[FAIL] zero length field name in format
> cd your/rose
> git co <this-branch>
> export ROSE_HOME=your/rose
> rose suite-run
```
Also checked that I haven't used format in changing 2019.01.5 → .6 anywhere else.
=> make cylc8 check compatible with python 2.6

metomi/rose/date.py, metomi/rose/date_cli.py, metomi/rose/tests/test_date_cli.py
Looks like the `Reporter()` instance didn't check out the way we would have expected it to, easier just to `print()` for the time being.
=> date: send warning to stderr not stdout

metomi/rose/suite_engine_procs/cylc.py
cylc.rose is not installed.
Proved horrendous to test - @dpmatthews  - can you test manually, whilst @oliver-sanders checks for Python goodness?
=> Allow get_task_auth (used by fcm make) to return None if

sphinx/api/configuration/suite.rst, sphinx/conf.py, sphinx/glossary.rst, sphinx/hyperlinks.rst, sphinx/tutorial/rose/configurations.rst, sphinx/tutorial/rose/summary.rst
Updated instersphinx mapping
Fixed egregious instances of "Cylc Suite"
Closes #2457 
Marked as blocked until after Cylc 8.0.0 docs are changed to "stable"
=> Changed Links to point to Cylc 8 "stable"

.github/actions/install-libs/action.yml
Install the maintenance branches of cylc-rose etc on both pull request or push to 2.0.x
This should fix current tests failures on push to 2.0.x
=> GH Actions: Fix wrong libs versions installed on push to 2.0.x

CHANGES.md, metomi/rose/__init__.py
For some reason the second stage of the release process was skipped, which is impossible. Trying reverting and re-doing.
This reverts commit 8a4c0c4e09374f3bae480d07bf3630352cea178c, reversing changes made to 0081e2256a3aaa205a4ad0037645538c0534bb1b.
=> Revert #2637

tox.ini
https://stackoverflow.com/questions/74558565/flake8-error-code-supplied-to-ignore-option-does-not-match-a-z1-30
=> Fix flake8 v6 problem

metomi/rose/date_cli.py, metomi/rose/tests/test_date_cli.py
* Integer is not a valid isodatetime calendar so we shouldn't pass it through as an env var.
* Closes #2665
=> rose date: fix issue when used with integer cycling workflows

.github/actions/install-libs/action.yml, CHANGES.md, metomi/rose/macros/rule.py, metomi/rose/tests/macros/test_py2_compat_types.py
Closes #2662 .
Following the instructions in the issue the following error is seen:
```
Invalid trigger expression: this < 1
```
The underlying cause is at `metomi/rose/macros/rule.py:214` is that type comparisons are not the same at Python 3 for base types as they are at Python 2.
```
(Pdb) template.render(rule_id_values)
*** TypeError: '<' not supported between instances of 'str' and 'int'
```
@oliver-sanders  suggested the following workarounds (in order of preference):
> Order of preference:
> 1a. Try to overwrite the str. float, bool & int, __lt__, __gt__, __ge__, __le__ methods used by Jinja2. 
> 1b. You may be able to do this by subclassing str, float, int etc as I started.
>       You may be able to do this by redefining them in the Python environment before calling Jinja2.
>
> 2. …
=> Macro validation fix

t/rosa-svn-post-commit/00-basic.t, t/rosa-svn-post-commit/03-unicode.t
* Disable stderr tests until sqlalchemy has been upgraded to version 2 and deprecation warnings addressed
* See https://github.com/metomi/rose/issues/2674
=> sqlalchemy: disable stderr tests

metomi/rose/apps/rose_bunch.py, sphinx/api/built-in/rose_bunch.rst, t/rose-task-run/31-app-bunch.t, t/rose-task-run/31-app-bunch/flow.cylc, t/rose-task-run/43-bunch-check-flows.t, t/rose-task-run/44-bunch-incremental.t
Closes #2698 
Two related issues:
=> Bunch: Incremental mode tweaks

CHANGES.md, metomi/rosie/ws_client_auth.py, setup.cfg
Closes #2661 
- Replace `libsecret` with `keyring`
- Remove broken zenity dialogs
- Fix GPG Agent Store type mishandling leftover from Python 2->3 upgrade
=> Fix Rosie password caching

sphinx/index.rst
Do we still want this?
Perhaps it's worth me reading this cover to cover at some point and jotting down anything else we might want rid of.
I've just noted a reference to file installation in the slides, for example. Will create a new issue later, but I think that this is required now.
=> Remove release candidate warning from docs

CHANGES.md, metomi/rose/rose.py, metomi/rose/tests/test_rose.py, tox.ini
Exactly the same as https://github.com/cylc/cylc-flow/pull/5727
=> Add handling for ROSE_PYTHONPATH

CONTRIBUTING.md, metomi/rosie/tests/test_suite_id.py, mypy.ini, setup.cfg
Closes https://github.com/cylc/cylc-admin/issues/182
Added flake8-type-checking library to project and resolved issues it identified.
Updates CONTRIBUTING.md file.
=> Flake8 type checking

lib/python/rosie/svn_pre_commit.py, sphinx/installation.rst, t/rosa-svn-pre-commit/04-aliases.t
Allow alternate usernames in order to support migrating a roses repository to a place with different auth.
=> Support alternate usernames in pre-commit

t/rose-task-run/44-bunch-incremental.t
I think that the second task (which is supposed to keep the workflow in a running state) was finishing too quickly on CI and the workflow was shutting down prematurely.
=> Fix Flaky test rose-task-run/44

metomi/rose/config_processors/fileinstall.py, metomi/rose/job_runner.py
One out of the triplet of PRs which closes https://github.com/cylc/cylc-rose/issues/274
* https://github.com/cylc/cylc-flow/pull/5868
* https://github.com/cylc/cylc-rose/pull/276
---
* Allow Rose file installation to be called by code which already has an event loop running by scheduling coroutines to run in the background (i.e. schedule but don't await).
* The calling code can list these tasks using `asyncio.all_tasks()` and await them as appropriate.
* Addresses https://github.com/cylc/cylc-rose/issues/274
---
For testing instructions see the cylc-flow PR.
=> fileinstall: run coros in the background if loop already running

CHANGES.md, lib/html/template/rosie-disco/prefix-index.html
By having double quotes in rose-suite.info you could inject arbitrary HTML into rosie disco.
In this example, the description contained
```
=the PDF document is displayed in the task "add_link_to_plots".
=--------------------------------------------------------------------
=There follows a description of template variables in
```
You can see how everything after 'in the task' is cut (and actually every word following this has become an attribute on the HTML element and caused the status bit to bleed into the element content)
I've tested out this fix by just running `lib/html/template/rosie-disco/prefix-index.html` through Jinja2 before and after
=> Fix unescaped content injection in rosie disco

sphinx/tutorial/rose/metadata.rst
Value hints gives a list of possible values, like a non-exclusive version of `value-titles`.
Served locally at <my-domain>/rose-doc/rose 2.2.0/html/tutorial/rose/metadata.html#admonition-4
[Reference for `value-titles`](https://metomi.github.io/rose/doc/html/api/configuration/metadata.html#rose:conf:rose-meta.conf[SETTING]value-hints)
P.S. Slide-builder is broken.
=> Docs: fix misleading tip

sphinx/api/built-in/rose_prune.rst
* Closes #2724
* The deprecation notice was first introduced here: https://github.com/metomi/rose/pull/1571/files#diff-6fcfe208ef088355e3a673de4c4bde527661154715f6351f6f9fbc2673373859R483-R489
=> docs: fix deprecation version

.github/workflows/test.yml
Python 3.7 no longer supported on latest MacOS runner
=> GH Actions: bump MacOS Python version

.github/workflows/test.yml, metomi/rose/config_processors/fileinstall.py, metomi/rose/loc_handlers/fs.py, metomi/rose/loc_handlers/git.py, metomi/rose/loc_handlers/namelist.py, metomi/rose/loc_handlers/rsync.py, sphinx/api/configuration/file-creation.rst, sphinx/installation.rst, t/rose-app-run/05-file.t, t/rose-app-run/06-namelist.t, t/rose-app-run/15-file-permission.t, t/rose-app-run/28-git.t
Work in progress!
Aims to address #1419.
I'm not that happy with the configuration syntax, although I am happy with the three main elements of it as elements.
The mechanism itself uses filtering and either partial clones or proper sparse checkouts where the Git version allows.
=> Git file install: support for file creation from Git repositories

metomi/rose/config_processors/fileinstall.py, metomi/rose/job_runner.py, t/workflow-file-install/00-install.t, t/workflow-file-install/test_header
(built on #2754)
Closes #2784
(hopefully this does it...)
job-runner: move finally block within async code
* The job_runner is async now and runs in the background (i.e. you have to await any active tasks if you want it to be synchronous).
* This means the `finally` block was run during the operation rather than after it.
* The solution is to inline this with the async code.
=> job-runner: fix async interaction

.coveragerc, metomi/rose/macros/rule.py, metomi/rose/tests/macros/test_rule.py, t/rose-metadata-check/12-template-variables.t
... at the start of rose metadata-check to prevent the space being a violation of the rose mini-language.
closes #2737
=> Replace "template variables" with "template_variables"

.mailmap, CONTRIBUTING.md, sphinx/installation.rst
Changed 2 lines in [the docs](https://metomi.github.io/rose/doc/html/installation.html#configuring-rose) for configuring rose:
`/etc/.metomi/rose.conf` --> `/etc/rose.conf` \
`$ROSE_SITE_CONF_PATH/.metomi/rose.conf` --> `$ROSE_SITE_CONF_PATH/rose.conf`
The [docstring](https://metomi.github.io/rose/doc/html/api/configuration/site-and-user.html#rose:file:rose.conf) is correct.
Cheers!
=> Docs: correct options for possible location of `rose.conf`

metomi/rose/loc_handlers/git.py, metomi/rose/popen.py, metomi/rose/tests/test_git.py
Closes #2809 - fixes `rose app-run` and `rose task-run` crashing if git is not installed
=> Fix traceback when git is not installed

sphinx/installation.rst
=> update / fix installation instructions

sphinx/conf.py, sphinx/hyperlinks.txt, sphinx/tutorial/rose/configurations.rst, sphinx/tutorial/rose/furthertopics/failif-warnif.rst, sphinx/tutorial/rose/furthertopics/rose-stem-tutorial.rst, sphinx/tutorial/rose/furthertopics/rose-stem.rst
* Avoid displaying `:orphan:` directive in built pages.
* Remove unecessary includes for `hyperlinks.rst`.
Built copy at: https://wwwspice/~tim.pillinger/doc/rose/rose%202.4.0.dev/html/tutorial/rose/configurations.html
According to [this thread](https://github.com/readthedocs/readthedocs.org/issues/809) on readthedocs this is a problem with including RST metadata.
=> Fix.orphan

metomi/rose/apps/fcm_make.py
Removed from std lib at Python 3.13: https://docs.python.org/3/library/pipes.html
=> Remove `pipes` usage

sphinx/tutorial/rose/furthertopics/command-keys.rst, sphinx/tutorial/rose/furthertopics/polling.rst, sphinx/tutorial/rose/furthertopics/rose-arch.rst, sphinx/tutorial/rose/furthertopics/rose-bunch.rst, sphinx/tutorial/rose/furthertopics/rose-stem-tutorial.rst, sphinx/tutorial/rose/suites.rst
Replace https://github.com/metomi/rose/pull/2836
=> Remove reference to UTC mode

sphinx/tutorial/rose/furthertopics/command-keys.rst, sphinx/tutorial/rose/furthertopics/polling.rst, sphinx/tutorial/rose/furthertopics/rose-arch.rst, sphinx/tutorial/rose/furthertopics/rose-bunch.rst, sphinx/tutorial/rose/furthertopics/rose-stem-tutorial.rst, sphinx/tutorial/rose/suites.rst
#2837
> Remove reference to UTC mode (setting now sensibly defaults to true in Cylc) from workflows.
=> Cherry-pick #2837

.github/workflows/test.yml, t/rose-config-diff/00-basic.t
* Fixes test failures.
* Get Python from conda-forge rather than the OS vendor.
* Test with all supported Python versions.
* Requires https://github.com/cylc/release-actions/pull/100
* Fix the remaining Mac OS test failure by using a more stable `diff` output format.
Note, the Mamba environments are cached which should bring some speedup, but unfortunately, we won't feel this until we completely phase out the OS package managers (which I wasn't able to do).
=> actions: use mamba to provision Python environment

.github/workflows/test-conda-builds.yml, conda-environment.yml
Follow the pattern in cylc-flow:
* Define conda dependencies in a conda-environment.yml file.
* Test the env builds correctly in a GH action.
* Translate dependencies into conda-forge feedstock when releasing.
=> add conda environment file

metomi/rose/config.py, metomi/rose/macro.py, t/rose-app-upgrade/14-same-transformation-applied-to-opt-config.t, t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/app/example_app/opt/rose-app-demo.conf, t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/app/example_app/rose-app.conf, t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/rose-meta/example_meta/HEAD/rose-meta.conf, t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/rose-meta/example_meta/versions.py, t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/rose-meta/example_meta/vn1.0/rose-meta.conf
* If a setting (e.g. `namelist:a=b`) is present in a ConfigNodeDiff, but its parent (e.g. `namelist:a`) is not. Then the state and comments of parent node may not be present in the diff if they have not changed.
* As a result the state and comments of the parent node may be incorrect in the output generated by `get_as_opt_config`.
* This commit detects parent nodes that are not present in the diff and adds an option to transfer them from a provided node.
* closes https://github.com/metomi/rose/issues/2853
=> ConfigNodeDiff.get_as_opt_config: preserve parent attributes

.github/workflows/2_auto_publish_release.yml
=> GH Actions: use latest `pypa/gh-action-pypi-publish`

metomi/rose/rose.py, setup.cfg
* Remove `rosie go` and `rosie disco` from the list of entry points so that they don't appear in the help docs.
* Both commands still return messages about being dead end-points.ls 
* `rosie disco`'s code remains unchanged at `metomi.rosie.ws`. Removing the entry point just removes it from the list show by `rosie help`.
* `rosie go` points to a file (`lib/python/rosie/browser/main.py`) which [I removed in 2018](https://github.com/metomi/rose/pull/2286)!
* Make the help docs show where commands have aliases.
=> Remove rosie go from the list of entry points

metomi/rosie/ws_client_cli.py
Fix breakage caused by https://github.com/metomi/rose/pull/2903
Turns out this code is called by other command(s).
=> rosie ls: fix command breakage
